from pathlib import Path
import sys,json,base64,time
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from browser_helpers import ROOT,offline_html,launch
from playwright.sync_api import sync_playwright
results=[]
def ck(name,value,detail=None):
 results.append({'test':name,'passed':bool(value),'detail':detail}); print(('PASS' if value else 'FAIL'),name,str(detail or '')[:150],flush=True)
with sync_playwright() as pw:
 browser=launch(pw);page=browser.new_page(viewport={'width':1280,'height':800})
 page.on('dialog',lambda d:d.accept());errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 html=offline_html(ROOT/'index.html').replace('requestAnimationFrame(frame);','window.__qaFrame=frame;')
 page.set_content(html,wait_until='domcontentloaded');page.wait_for_function('window.__industrial012Ready===true',timeout=15000)
 info=page.evaluate('__deliveryTest.v0102.info()');(ROOT/'tests/layout012.json').write_text(json.dumps(info,ensure_ascii=False,indent=2))
 ck('Industrial load all assets', info['ready'] and not info['error'])
 ck('Correct main menu version',page.locator('.edition').inner_text().startswith('V0.10.2 ONLINE'))
 ck('Correct title','V0.10.2' in page.title())
 ck('Six industrial delivery addresses',[a['num'] for a in info['audit']]==list(range(107,113)))
 ck('Factory density >= 24 buildings',sum(o['role'] in ['main','infill'] for o in info['placements'])>=24)
 ck('Industrial props present',sum(o['role']=='prop' for o in info['placements'])>=6)
 ck('Buildings do not overlap',page.evaluate('__deliveryTest.v0102.overlapAudit()')==[])
 ck('No road furniture in receiving bays',not info['furnitureConflicts'],info['furnitureConflicts'])
 ck('All footprints clear of road surfaces',all(i['ok'] for i in page.evaluate('__deliveryTest.v0102.roadAudit()')))
 for a in info['audit']:
  ck(f"#{a['num']} facade faces road",a['frontDot']>.995,a['frontDot'])
  ck(f"#{a['num']} full-size factory",a['width']>=17 and a['depth']>=11,a)
  ck(f"#{a['num']} setback 2-4m",2<=a['frontSetback']<=4 and a['apertureFromKerb']>=.3)
 page.evaluate('__deliveryTest.v0102.reset();__deliveryTest.v0102.render()')
 ck('18 initial parcels and jobs',page.evaluate('({n:__deliveryTest.snapshot().houses.length,s:__deliveryTest.snapshot().stock})')=={'n':18,'s':18})
 ck('Jump hidden while driving',not page.locator('#boardBtn').is_visible())
 page.evaluate("__deliveryTest.v0102.view('outside')")
 ck('Jump shown while walking',page.locator('#boardBtn').is_visible())
 page.evaluate("__deliveryTest.v0102.view('cargo')")
 ck('Jump shown inside cargo',page.locator('#boardBtn').is_visible())
 for n in range(107,113):
  page.evaluate('__deliveryTest.v0102.reset()')
  opts={'y':2.6} if n in [108,112] else {}
  shot=page.evaluate('(a)=>__deliveryTest.v0102.fire(a.n,a.o)',{'n':n,'o':opts})
  page.evaluate('__deliveryTest.advance(1)')
  snap=page.evaluate('__deliveryTest.snapshot()');box=page.evaluate('(id)=>__deliveryTest.v0102.parcel(id)',shot['id'])
  ck(f'Actual parcel flight accepted #{n}', any(h['num']==n and h['done'] for h in snap['houses']) and snap['state']['delivered']==1,box)
  # Re-running cannot increment the same order twice.
  page.evaluate('__deliveryTest.advance(.7)');ck(f'No repeated reward #{n}',page.evaluate('__deliveryTest.snapshot().state.delivered')==1)
 page.evaluate('__deliveryTest.v0102.reset()')
 shot=page.evaluate('__deliveryTest.v0102.fire(107,{order:101})');page.evaluate('__deliveryTest.advance(1)')
 snap=page.evaluate('__deliveryTest.snapshot()');ck('Wrong-address parcel rejected',snap['state']['delivered']==0 and not next(x for x in snap['houses'] if x['num']==107)['done'])
 ck('Guest cannot award a delivery',page.evaluate('__deliveryTest.v0102.guestAttempt(107)')=={'delivered':False,'scoreChanged':False})
 for n in [101,113,111]:
  page.evaluate('__deliveryTest.v0102.reset()');shot=page.evaluate('(n)=>__deliveryTest.v0102.fire(n)',n);page.evaluate('__deliveryTest.advance(.8)')
  snap=page.evaluate('__deliveryTest.snapshot()');pane=next((x for x in page.evaluate('__deliveryTest.v0102.panes()') if x['num']==n and x['index']==0),None)
  ck(f'Glass parcel flight #{n}', next(x for x in snap['houses'] if x['num']==n)['done'],page.evaluate('(id)=>__deliveryTest.v0102.parcel(id)',shot['id']))
  ck(f'Glass hole retained #{n}',pane is not None and len(pane['holes'])>0,pane)
  if pane:
   image=page.evaluate('(n)=>__deliveryTest.v0102.texture(n)',n);(ROOT/f'screenshots/glass-texture-{n}.png').write_bytes(base64.b64decode(image.split(',')[1]))
 page.evaluate('__deliveryTest.v0102.reset();__deliveryTest.v0102.damageWindow(101,0,0,0)')
 old=page.evaluate('__deliveryTest.v0102.panes().find(p=>p.num===101&&p.index===0).holes[0].r')
 page.evaluate('__deliveryTest.v0102.damageWindow(101,0,.45,0)')
 new=page.evaluate('__deliveryTest.v0102.panes().find(p=>p.num===101&&p.index===0).holes[0].r');ck('Near impact enlarges existing hole',new>old,{'old':old,'new':new})
 page.evaluate('for(let i=0;i<30;i++)__deliveryTest.v0102.damageWindow(101,0,Math.sin(i)*.95,Math.cos(i)*.8)')
 ck('Bounded holes <= 4 per pane',all(len(x['holes'])<=4 for x in page.evaluate('__deliveryTest.v0102.panes()')))
 image=page.evaluate('__deliveryTest.v0102.texture(101)');(ROOT/'screenshots/glass-multiple.png').write_bytes(base64.b64decode(image.split(',')[1]))
 page.evaluate('__deliveryTest.v0102.reset()');ck('Restart clears all cracks',all(not p['holes'] for p in page.evaluate('__deliveryTest.v0102.panes()')))
 for n in range(107,113):
  page.evaluate('__deliveryTest.v0102.reset()');hit=page.evaluate('(n)=>__deliveryTest.v0102.collide(n,27.78,1.0)',n)
  ck(f'Enlarged collider blocks side entry #{n}',not hit['overlap'] and abs(hit['speed'])<1,hit)
 page.evaluate('__deliveryTest.v0102.reset();__deliveryTest.roads09.place(224,8,0,0,0);__deliveryTest.v0102.render();__deliveryTest.v0102.render();')
 lit=page.evaluate('__deliveryTest.v0102.lighting()');ck('Bridge cover darkens truck',lit['cover']<1 and lit['shade']<.9,lit)
 page.evaluate('__deliveryTest.roads09.place(224,-24,0,0,0);__deliveryTest.v0102.render();__deliveryTest.v0102.render()');lit=page.evaluate('__deliveryTest.v0102.lighting()');ck('Leaving bridge restores light smoothly',lit['cover']==1 and lit['shade']>.9,lit)
 page.evaluate('__deliveryTest.v0102.reset();__deliveryTest.v0102.cameraAt(109)');page.screenshot(path=str(ROOT/'screenshots/frontage-109.png'))
 page.evaluate('__deliveryTest.v0102.glassCamera(111)');page.screenshot(path=str(ROOT/'screenshots/glass-before.png'))
 page.evaluate('__deliveryTest.v0102.damageWindow(111,0,.15,.1);__deliveryTest.v0102.glassCamera(111)');page.screenshot(path=str(ROOT/'screenshots/glass-after.png'))
 for width,height in [(390,844),(844,390),(320,640)]:
  page.set_viewport_size({'width':width,'height':height});page.evaluate('__qaFrame(performance.now()+16);__deliveryTest.v0102.cameraAt(109)')
  metrics=page.evaluate('({w:innerWidth,h:innerHeight,game:document.getElementById("game").getBoundingClientRect().toJSON(),over:document.documentElement.scrollWidth>innerWidth})')
  ck(f'Viewport {width}x{height}', not metrics['over'] and abs(metrics['game']['height']-height)<1,metrics)
  ck(f'Drive jump stays hidden {width}x{height}',not page.locator('#boardBtn').is_visible())
  if width==390: page.screenshot(path=str(ROOT/'screenshots/phone-factory.png'))
 page.set_viewport_size({'width':1280,'height':800});page.evaluate('__qaFrame(performance.now()+16);__deliveryTest.pause()')
 ck('Lighting quality option present',page.locator('#lighting012').is_visible());page.locator('#lighting012').click();page.evaluate('__deliveryTest.v0102.render()');ck('Economy shadows limited',page.evaluate('__deliveryTest.v0102.lighting().draws')<=1)
 ck('Pause exit present',page.locator('#pauseExit091').is_visible());page.locator('#pauseExit091').click();ck('Exit returns to menu',page.locator('#menu').is_visible());page.locator('#startBtn').click();ck('Can restart without page reload',page.evaluate('__deliveryTest.snapshot().state.mode')=='playing')
 ck('No WebGL error',page.evaluate('__deliveryTest.glError()')==0)
 ck('No page errors',not errors,errors)
 (ROOT/'tests/V0102_RESULTS.json').write_text(json.dumps({'checks':results,'passed':sum(x['passed'] for x in results),'total':len(results),'errors':errors},ensure_ascii=False,indent=2))
 print('SUMMARY',sum(x['passed'] for x in results),'/',len(results),flush=True)
 browser.close()
