/* Crash Delivery V0.12.3 — native world extension. All road/rail/landscape
 * meshes originate from the user's Kenney GLBs. Authority stays with host.
 * No network requests except local asset URLs; no engine replacement. */
const WORLD123={ready:false,clock:0,rail:null,trains:[],units:[],crossings:[],static:[],terrain:[],terrainGrid:new Map(),infill:[],trees:0,assets:0,draws:0,wreck:null,blastId:0,guestBlast:0,lastSafe:{p:[3.2,.12,72],yaw:0},safeClock:0};
const W123_MODELS=__MODEL_MANIFEST__;
const w123mod=(x,n)=>((x%n)+n)%n;
function w123MeshTransform(raw,m,b=new MeshBuilder()){for(let i=0;i<raw.length;i+=9)b.a.push(...M.point(m,raw.slice(i,i+3)),...road122Normal(m,raw.slice(i+3,i+6)),...raw.slice(i+6,i+9));return b;}
async function w123Load(kind){
 const palette=await new Promise((resolve,reject)=>{const im=new Image();const timer=setTimeout(()=>reject(Error(kind+' 调色板超时')),25000);im.onload=()=>{clearTimeout(timer);try{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);resolve({pixels:ctx.getImageData(0,0,c.width,c.height).data,w:c.width,h:c.height});}catch(e){reject(e);}};im.onerror=()=>{clearTimeout(timer);reject(Error(kind+' 调色板不存在'));};im.src='./assets/kenney-'+kind+'/Textures/colormap.png';});
 const loader=new RoadGLB09(palette.pixels,palette.w,palette.h);let cursor=0;
 const worker=async()=>{while(cursor<W123_MODELS[kind].length){const name=W123_MODELS[kind][cursor++],url='./assets/kenney-'+kind+'/'+name+'.glb',controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const res=await fetch(url,{signal:controller.signal});if(!res.ok)throw Error(url+' HTTP '+res.status);const bytes=new Uint8Array(await res.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=32768)text+=String.fromCharCode(...bytes.subarray(i,i+32768));const a=loader.load(name,btoa(text));a.bounds=ind012Bounds(a);CITY012.assets.set(kind+'/'+name,a);CITY012.meshes.set(kind+'/'+name,renderer.mesh(a.b));WORLD123.assets++;}catch(e){throw Error(name+': '+e.message);}finally{clearTimeout(timer);}}};await Promise.all([worker(),worker(),worker()]);
}
function w123Static(kind,name,p,yaw,scale,label='landscape',raw=false){const a=city012Asset(kind,name);const m=raw?scaled(M.model(p,[0,yaw,0]),scale):city012Model(kind,name,p,yaw,scale);WORLD123.static.push({kind,name,m,p:p.slice(),label,r:Math.hypot(a.bounds.size[0]*(Array.isArray(scale)?scale[0]:scale),a.bounds.size[2]*(Array.isArray(scale)?scale[2]:scale))/2,height:a.bounds.size[1]*(Array.isArray(scale)?scale[1]:scale)});return m;}
function w123Rail(){
 const r=12.8,x0=152,x1=216,z0=124,z1=316,S=3.2,points=[];const railBuilder=new MeshBuilder();WORLD123.railTiles=[];
 const addTile=(name,p,yaw,scale)=>{const a=city012Asset('trains',name),m=scaled(M.model(p,[0,yaw,0]),scale);w123MeshTransform(a.b.a,m,railBuilder);WORLD123.railTiles.push({name,p,yaw,scale,m});};
 const straight=(a,b)=>{const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),yaw=Math.atan2(dx,dz),steps=Math.ceil(len/(4*S));for(let i=0;i<steps;i++){const t=i/steps,p=[a[0]+dx*t,S-.2,a[1]+dz*t];const crossing=Math.abs(dx)<.001&&Math.abs(p[2]+dz/steps*.5-168)<16;addTile(crossing?'railroad-rail-straight':'railroad-straight',p,yaw,[S,S,len/steps/4]);}for(let i=0;i<Math.ceil(len/2);i++){const t=i/Math.ceil(len/2);points.push([a[0]+dx*t,.12,a[1]+dz*t]);}};
 const corner=(x,z,yaw)=>{const m=scaled(M.model([x,0,z],[0,yaw,0]),S);addTile('railroad-corner-large',[x,S-.2,z],yaw,S);for(let i=0;i<24;i++){const t=i/24*Math.PI/2,q=M.point(m,[-4+4*Math.cos(t),0,4*Math.sin(t)]);points.push([q[0],.12,q[2]]);}};
 straight([x1,z0+r],[x1,z1-r]);corner(x1,z1-r,0);straight([x1-r,z1],[x0+r,z1]);corner(x0+r,z1,-Math.PI/2);straight([x0,z1-r],[x0,z0+r]);corner(x0,z0+r,Math.PI);straight([x0+r,z0],[x1-r,z0]);corner(x1-r,z0,Math.PI/2);points.push(points[0].slice());
 WORLD123.rail=polyPath(points,'铁路环线');WORLD123.trackMesh=renderer.mesh(railBuilder);
 const models=[['train-diesel-a','train-carriage-container-red','train-carriage-lumber','train-carriage-coal'],['train-electric-city-a','train-electric-city-b','train-electric-city-c']];
 WORLD123.trains=models.map((names,i)=>{let offset=0;const cars=names.map((name,j)=>{const a=city012Asset('trains',name),half=a.bounds.size[2]*S/2;if(j)offset+=half+.30;const o={name,offset,hw:a.bounds.size[0]*S/2,hl:half,height:a.bounds.size[1]*S,scale:S};offset+=half+.30;return o;});return {id:i,label:i?'城际客运':'工业货运',start:WORLD123.rail.len*(i?.55:.05),s:WORLD123.rail.len*(i?.55:.05),speed:10,cars,length:offset};});
 WORLD123.crossings=[152,216].map((x,id)=>({id,x,z:168,s:w123NearestRail([x,.12,168]).s,closed:false,warning:false,gate:Math.PI/2,eta:Infinity}));w123Positions();
 // Native warning boards and signals sit outside the 16 m driveable road.
 const b=new MeshBuilder();for(const c of WORLD123.crossings)for(const side of [-1,1]){for(const [name,x,z,yaw,scale] of [['road-sign-warning',c.x-side*10,c.z+side*10,-side*Math.PI/2,10],['traffic-light',c.x-side*7.5,c.z+side*9.7,-side*Math.PI/2,8]]){const a=road09.assets.get(name);w123MeshTransform(a.b.a,scaled(M.model([x,.08,z],[0,yaw+Math.PI/2,0]),scale),b);}}WORLD123.crossingMesh=renderer.mesh(b);
 const barrier=road09.assets.get('construction-barrier');WORLD123.gateMesh=renderer.mesh(barrier.b);
}
function w123NearestRail(p){let best={d:Infinity,s:0};if(!WORLD123.rail)return best;const pts=WORLD123.rail.points;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],dx=b[0]-a[0],dz=b[2]-a[2],t=clamp(((p[0]-a[0])*dx+(p[2]-a[2])*dz)/(dx*dx+dz*dz||1),0,1),q=V.lerp(a,b,t),d=Math.hypot(q[0]-p[0],q[2]-p[2]);if(d<best.d)best={d,s:WORLD123.rail.lens[i-1]+V.len(V.sub(q,a)),q};}return best;}
function w123Positions(){WORLD123.units=[];for(const t of WORLD123.trains)for(const [i,o]of t.cars.entries()){const q=pathAt(WORLD123.rail,w123mod(t.s-o.offset,WORLD123.rail.len));WORLD123.units.push({...o,p:q.p,yaw:q.yaw,train:t.id,index:i});}}
function w123Clear(o,pad=1){if(!city012LotRoads(o,pad))return false;if(w123NearestRail([o.x,0,o.z]).d<Math.hypot(o.hw,o.hd)+5.5)return false;if(industrial012.reserved.some(r=>ind012Overlap(o,r,pad)))return false;if(SUB011.homes.some(r=>ind012Overlap(o,r,pad)))return false;return true;}
function w123Infill(){
 // Fill the eastern trial surroundings first, then remaining outer-city blocks.
 const targets=[],trialLots=[],railLots=[];for(let z=-70;z<=112;z+=27)for(let x=140;x<=316;x+=27)trialLots.push([x,z]);for(let z=128;z<=300;z+=27)for(let x=140;x<=316;x+=27)railLots.push([x,z]);for(let i=0;i<Math.max(trialLots.length,railLots.length);i++){if(trialLots[i])targets.push(trialLots[i]);if(railLots[i])targets.push(railLots[i]);}for(let z=-252;z<=252;z+=28)for(let x=-252;x<=140;x+=28)targets.push([x+5,z+6]);let serial=12000;
 for(const [x,z]of targets){if(WORLD123.infill.length>=62)break;const name='building-'+'abcdefghijkln'[serial%13],a=city012Asset('commercial',name),bb=a.bounds,scale=Math.min(8.5,13.5/bb.size[0],14/bb.size[2]),d=districtAt(x,z),yaw=serial%2?Math.PI/2:0,h={x,z,yaw,num:serial++,deliverable:false,done:false,style:'market',district:d,gates:[],commercial012:true},o={name:'commercial/'+name,x,z,yaw,scale,hw:bb.size[0]*scale/2,hd:bb.size[2]*scale/2,height:bb.size[1]*scale,minY:.12,maxY:.12+bb.size[1]*scale,h,role:'world-infill',commercial012:true,portals:[],setback:2.5};if(!w123Clear(o,2))continue;o.m=sub011Model(o);houses.push(h);sub011Adopt(o);CITY012.commercial.push(o);WORLD123.infill.push(o);}
}
function w123TerrainIndex(o,m){const raw=city012Asset('terrain',o.name).b.a;let count=0;for(let i=0;i<raw.length;i+=27){const a=M.point(m,raw.slice(i,i+3)),b=M.point(m,raw.slice(i+9,i+12)),c=M.point(m,raw.slice(i+18,i+21)),n=V.norm(V.cross(V.sub(b,a),V.sub(c,a))),den=(b[0]-a[0])*(c[2]-a[2])-(b[2]-a[2])*(c[0]-a[0]);if(n[1]<.12||Math.abs(den)<.00001)continue;const t={a,b,c,n,den,tile:-20000-WORLD123.terrain.length,road:false,minX:Math.min(a[0],b[0],c[0]),maxX:Math.max(a[0],b[0],c[0]),minZ:Math.min(a[2],b[2],c[2]),maxZ:Math.max(a[2],b[2],c[2])};for(let x=Math.floor(t.minX/16);x<=Math.floor(t.maxX/16);x++)for(let z=Math.floor(t.minZ/16);z<=Math.floor(t.maxZ/16);z++){const key=x+','+z;if(!WORLD123.terrainGrid.has(key))WORLD123.terrainGrid.set(key,[]);WORLD123.terrainGrid.get(key).push(t);}count++;}o.surfaceTriangles=count;}
function w123Terrain(){
 const names=['block-grass-low-large','block-grass-curve-low','block-grass-low-hexagon','block-grass-large-slope','block-grass-large-slope-narrow'];
 // Shallow landscaped ground inside the playable region: no hidden tall steps.
 for(let z=-306;z<=324;z+=35)for(let x=-310;x<=324;x+=35){const index=WORLD123.terrain.length,name=names[index%names.length],size=18+(index%3)*3,o={x,z,hw:size*.5,hd:size*.5,yaw:0,name};if(!w123Clear(o,2.3))continue;const a=city012Asset('terrain',name),sc=[size/a.bounds.size[0],.72/a.bounds.size[1],size/a.bounds.size[2]],m=w123Static('terrain',name,[x,-.31,z],0,sc,'landscape');o.top=.41;o.m=m;w123TerrainIndex(o,m);WORLD123.terrain.push(o);
  for(let j=0;j<3;j++){const dx=(j-1)*size*.24,dz=(j%2?1:-1)*size*.18,tree=j%2?'tree-pine':'tree',p=[x+dx,.45,z+dz];w123Static('environment',tree,p,index*.7+j,3.1+(index%4)*.35,'vegetation');WORLD123.trees++;}
 }
 // Large natural boundaries stay beyond the playable square; no hill blocks a highway.
 for(let i=0;i<44;i++){const a=i/44*TAU,dist=520+28*Math.sin(i*2.7),p=[Math.cos(a)*dist,-32,Math.sin(a)*dist],name=['block-grass-large-slope','block-grass-large-tall','block-grass-large-slope-steep','block-grass-large'][i%4],asset=city012Asset('terrain',name),sc=[(75+i%4*9)/asset.bounds.size[0],(34+i%5*8)/asset.bounds.size[1],(67+i%3*12)/asset.bounds.size[2]];w123Static('terrain',name,p,-a,sc,'boundary');}
 // Railway margins and the workshop transition use the already imported trees/rocks.
 for(let i=0;i<40;i++){const s=i/40*WORLD123.rail.len,q=pathAt(WORLD123.rail,s),right=[-q.dir[2],0,q.dir[0]],p=V.add(q.p,V.mul(right,7.5));const o={x:p[0],z:p[2],hw:1.3,hd:1.3,yaw:0};if(!w123Clear(o,.7))continue;w123Static('environment',i%3?'tree-pine':'rocks',[p[0],.08,p[2]],i,3.3,'vegetation');WORLD123.trees++;}
 // A few real freight props near the loop, not in the train envelope.
 for(let i=0;i<12;i++){const x=179+(i%3)*5,z=210+Math.floor(i/3)*8,o={x,z,hw:2,hd:2,yaw:0};if(!w123Clear(o,1))continue;w123Static('environment',i%2?'crate-strong':'pipe',[x,.1,z],i%2*Math.PI/2,3.5,'detail');}
}
function w123TerrainLevels(x,z){const out=[];for(const t of WORLD123.terrainGrid.get(Math.floor(x/16)+','+Math.floor(z/16))||[]){if(x<t.minX||x>t.maxX||z<t.minZ||z>t.maxZ)continue;const dx=x-t.a[0],dz=z-t.a[2],u=(dx*(t.c[2]-t.a[2])-dz*(t.c[0]-t.a[0]))/t.den,v=((t.b[0]-t.a[0])*dz-(t.b[2]-t.a[2])*dx)/t.den;if(u>=-.0001&&v>=-.0001&&u+v<=1.0001){const y=t.a[1]+u*(t.b[1]-t.a[1])+v*(t.c[1]-t.a[1]);if(y>.08&&!out.some(p=>Math.abs(p.y-y)<.001))out.push({y,n:t.n,tile:t.tile,road:false});}}return out;}
const w123OldLevels=road09Levels;road09Levels=function(x,z){return w123OldLevels(x,z).concat(w123TerrainLevels(x,z)).sort((a,b)=>a.y-b.y);};
function w123Overlap(a,b){if(a.p[1]+3.35<b.p[1]+.05||a.p[1]>b.p[1]+b.height-.1)return false;const ar=[Math.cos(a.yaw),0,-Math.sin(a.yaw)],af=[-Math.sin(a.yaw),0,-Math.cos(a.yaw)],br=[Math.cos(b.yaw),0,-Math.sin(b.yaw)],bf=[-Math.sin(b.yaw),0,-Math.cos(b.yaw)],d=V.sub(b.p,a.p);for(const axis of [ar,af,br,bf]){const ra=1.59*Math.abs(V.dot(ar,axis))+3.80*Math.abs(V.dot(af,axis)),rb=b.hw*Math.abs(V.dot(br,axis))+b.hl*Math.abs(V.dot(bf,axis));if(Math.abs(V.dot(d,axis))>ra+rb)return false;}return true;}
function w123BlastFX(pos){for(let i=0;i<14;i++){const a=i/14*TAU;addEffect(fireMeshes[i%3],V.add(pos,[Math.cos(a)*1.2,2.3,Math.sin(a)*1.2]),[Math.cos(a)*5,3+(i%3),Math.sin(a)*5],.75,1.5,2.8,1);}for(let i=0;i<12;i++)addEffect(i%2?smokeMesh:darkSmokeMesh,V.add(pos,[0,1,0]),[Math.sin(i)*2,2+i%4,Math.cos(i)*2],3.2,.8,4,.83);for(let i=0;i<12;i++){const name=['debris-bumper','debris-door','debris-tire'][i%3],mesh=CITY012.meshes.get('cars/'+name)||metalMesh;addDebris(mesh,V.add(pos,[0,1.5,0]),[Math.cos(i*2.4)*8,4+i%5,Math.sin(i*2.4)*8],[i,0,i*.3],4.5);}if(motion)state.shake=.25;noiseSound(.65,160,.65,'lowpass');tone(48,.65,'triangle',.45);}
function w123Wreck(){if(WORLD123.wreck||net.mode==='guest'||road09Duel())return;const pos=car.p.slice();WORLD123.wreck={p:pos,yaw:car.yaw,remaining:4.5};WORLD123.blastId++;car.hp=0;car.speed=0;car.velocity=[0,0,0];car.kick=[0,0,0];dislodgeBrick();state.brick=false;brickBody.placed=false;clearInputs();cancelCharge();state.explosions++;w123BlastFX(pos);
 const lost=cargo.splice(0);if(player.held&&state.view!=='outside'){lost.push(player.held);player.held=null;}for(const [i,p]of lost.entries()){const a=i*2.399963;Object.assign(p,{p:V.add(pos,[Math.cos(a)*(4.8+i%3),1.2+(i%4)*.4,Math.sin(a)*(4.8+i%3)]),v:[Math.cos(a)*3,3+i%4,Math.sin(a)*3],rot:[0,a,0],spin:[1,2,.7],age:0,thrown:true,pending:null,returnToDoor:false,lastHit:-1,hitNpc:null,rest012:null,blastBoosted:true});if(!packages.some(q=>q.id===p.id))packages.push(p);}showToast('列车撞击 · 车辆报废','货物已散落，救援即将到达',4);syncButtons();}
function w123Rescue(){const s=WORLD123.lastSafe;car.p=s.p.slice();car.yaw=s.yaw;car.roadPitch=0;car.speed=0;car.velocity=[0,0,0];car.kick=[0,0,0];car.hp=100;car.fault='';car.accel=[0,0,0];car.steer=0;car.roll=0;WORLD123.wreck=null;state.view='drive';player.p=[0,2.38,-.9];cameraBlend=0;clearInputs();state.score-=120;showToast('救援完成 · −$120','配送进度保留；散落包裹已标在地图上',4);syncButtons();}
function w123Crossings(dt){for(const c of WORLD123.crossings){let eta=Infinity,occupied=false;for(const t of WORLD123.trains){const ahead=w123mod(c.s-t.s,WORLD123.rail.len),past=w123mod(t.s-c.s,WORLD123.rail.len);if(past<t.length+7||ahead<8)occupied=true;eta=Math.min(eta,ahead/t.speed);}c.eta=eta;c.warning=occupied||eta<5.5;c.closed=occupied||eta<3.8;const target=c.closed?0:Math.PI/2;c.gate=mix(c.gate,target,1-Math.exp(-dt*4));if(c.warning&&!c.wasWarning&&Math.hypot(c.x-car.p[0],c.z-car.p[2])<80){tone(720,.12,'sine',.06);tone(540,.18,'sine',.05);}c.wasWarning=c.warning;}}
function w123Step(dt,oldCar){if(!WORLD123.ready||state.mode!=='playing'||road09Duel())return;if(net.mode==='guest'){w123Crossings(dt);w123HUD();return;}WORLD123.clock+=dt;const old=WORLD123.units;for(const t of WORLD123.trains)t.s=w123mod(t.s+t.speed*dt,WORLD123.rail.len);w123Positions();w123Crossings(dt);
 if(WORLD123.wreck){car.p=WORLD123.wreck.p.slice();car.speed=0;car.velocity=[0,0,0];WORLD123.wreck.remaining-=dt;if(WORLD123.wreck.remaining<=0)w123Rescue();}
 else {const n=Math.min(256,Math.max(1,Math.ceil((V.len(V.sub(car.p,oldCar.p))+12*dt+Math.abs(wrapAngle(car.yaw-oldCar.yaw))*4)/.35)));outer:for(let j=0;j<WORLD123.units.length;j++){const b=WORLD123.units[j],prev=old[j]||b;if(Math.hypot(car.p[0]-b.p[0],car.p[2]-b.p[2])>14+V.len(V.sub(car.p,oldCar.p)))continue;for(let i=0;i<=n;i++){const t=i/n,a={p:V.lerp(oldCar.p,car.p,t),yaw:oldCar.yaw+wrapAngle(car.yaw-oldCar.yaw)*t},q={...b,p:V.lerp(prev.p,b.p,t),yaw:prev.yaw+wrapAngle(b.yaw-prev.yaw)*t};if(w123Overlap(a,q)){w123Wreck();break outer;}}}
 if(!WORLD123.wreck&&WORLD123.clock-WORLD123.safeClock>1&&w123NearestRail(car.p).d>32){const q=road09Support(car.p[0],car.p[2],car.p[1],.1);if(q.road&&Math.abs(q.y-car.p[1])<.25){WORLD123.lastSafe={p:car.p.slice(),yaw:car.yaw};WORLD123.safeClock=WORLD123.clock;}}}w123HUD();}
function w123HUD(){const el=$('railAlert123');if(!el)return;const w=WORLD123.wreck,near=WORLD123.crossings.find(c=>c.warning&&Math.hypot(c.x-car.p[0],c.z-car.p[2])<50&&Math.abs(car.p[1]-.12)<3);el.hidden=state.mode!=='playing'||road09Duel()||(!w&&!near);el.dataset.wreck=String(!!w);if(w)el.innerHTML='车辆报废 · 救援 '+Math.max(1,Math.ceil(w.remaining))+' 秒<small>列车优先通行 · 散落快递可在地图上寻找</small>';else if(near)el.innerHTML='铁路道口 · 列车通行<small>请在红灯前等候，抢行会导致车辆报废</small>';}
function w123GateMatrix(c,side){return M.multiply(scaled(M.model([c.x-side*7.5,.7,c.z+side*7.5],[side*c.gate,side<0?Math.PI:0,0]),[6,3,32]),M.model([0,0,-.1125]));}
function w123BatchScenery(){const groups=new Map();for(const o of WORLD123.static){const cell=o.label==='boundary'?96:56,key=o.label+':'+Math.floor(o.p[0]/cell)+','+Math.floor(o.p[2]/cell);let g=groups.get(key);if(!g){g={label:o.label,b:new MeshBuilder(),min:[Infinity,Infinity,Infinity],max:[-Infinity,-Infinity,-Infinity]};groups.set(key,g);}const a=city012Asset(o.kind,o.name);w123MeshTransform(a.b.a,o.m,g.b);for(const x of [a.bounds.min[0],a.bounds.max[0]])for(const y of [a.bounds.min[1],a.bounds.max[1]])for(const z of [a.bounds.min[2],a.bounds.max[2]]){const p=M.point(o.m,[x,y,z]);for(let k=0;k<3;k++){g.min[k]=Math.min(g.min[k],p[k]);g.max[k]=Math.max(g.max[k],p[k]);}}}WORLD123.batches=[];for(const g of groups.values())WORLD123.batches.push({label:g.label,p:V.mul(V.add(g.min,g.max),.5),r:V.len(V.sub(g.max,g.min))*.5,mesh:renderer.mesh(g.b)});}
function w123Draw(){if(!WORLD123.ready||state.mode==='wardrobe')return;const f=V.norm(V.sub(at,eye));WORLD123.draws=0;const right=V.norm(V.cross(f,[0,1,0])),up=V.cross(right,f),tanY=Math.tan(renderer.fov/2),tanX=tanY*renderer.w/renderer.h;for(const o of WORLD123.batches||[]){const d=V.sub(o.p,eye),lim=o.label==='boundary'?770:o.label==='vegetation'?(quality==='low'?150:220):o.label==='detail'?95:380,along=V.dot(d,f);if(V.len(d)-o.r>lim||along<-o.r||Math.abs(V.dot(d,right))>Math.max(0,along)*tanX+o.r||Math.abs(V.dot(d,up))>Math.max(0,along)*tanY+o.r)continue;renderer.draw(o.mesh);WORLD123.draws++;}
 if(road09Duel())return;const d=V.sub([184,0,220],eye);if(V.len(d)<530&&V.dot(d,f)>-135){renderer.draw(WORLD123.trackMesh);renderer.draw(WORLD123.crossingMesh);}for(const u of WORLD123.units){if(V.len(V.sub(u.p,eye))>420)continue;const m=city012Model('trains',u.name,u.p,u.yaw,u.scale);renderer.draw(CITY012.meshes.get('trains/'+u.name),m);WORLD123.draws++;}for(const c of WORLD123.crossings){if(Math.hypot(c.x-eye[0],c.z-eye[2])>260)continue;for(const side of [-1,1]){renderer.draw(WORLD123.gateMesh,w123GateMatrix(c,side));if(c.warning&&Math.floor(WORLD123.clock*3)%2===0)renderer.draw(fireMeshes[0],scaled(M.model([c.x-side*7.5,3.8,c.z+side*9.7]),.23));}}
}
const w123CarBase=stepCar;stepCar=function(dt,predictionOnly=false){if(WORLD123.wreck&&!road09Duel()){car.speed=0;car.velocity=[0,0,0];car.kick=[0,0,0];return;}w123CarBase(dt,predictionOnly);};
const w123StepBase=step;step=function(dt){const old={p:car.p.slice(),yaw:car.yaw};w123StepBase(dt);w123Step(dt,old);};
const w123ResetBase=resetGame;resetGame=function(toMenu=false){w123ResetBase(toMenu);WORLD123.wreck=null;WORLD123.clock=0;WORLD123.safeClock=0;WORLD123.lastSafe={p:car.p.slice(),yaw:car.yaw};for(const t of WORLD123.trains)t.s=t.start;if(WORLD123.rail)w123Positions();w123HUD();};
const w123NetBase=netSnapshot;netSnapshot=function(target=null){const m=w123NetBase(target);if(WORLD123.ready)m.world123={clock:WORLD123.clock,progress:WORLD123.trains.map(t=>t.s),blast:WORLD123.blastId,wreck:WORLD123.wreck?{p:WORLD123.wreck.p.slice(),yaw:WORLD123.wreck.yaw,remaining:WORLD123.wreck.remaining}:null};return m;};
const w123ApplyBase=applyHostSnapshot;applyHostSnapshot=function(m){w123ApplyBase(m);if(!m.world123||m.seq!==net.lastWorldSeq||!WORLD123.ready)return;const w=m.world123;WORLD123.clock=w.clock;for(let i=0;i<WORLD123.trains.length;i++)if(Number.isFinite(w.progress?.[i]))WORLD123.trains[i].s=w123mod(w.progress[i],WORLD123.rail.len);if(w.blast>WORLD123.guestBlast){if(w.wreck)w123BlastFX(w.wreck.p);WORLD123.guestBlast=w.blast;}WORLD123.wreck=w.wreck;w123Positions();w123Crossings(.08);w123HUD();};
// Cosmetic guest interpolation between authoritative snapshots; never runs damage.
const w123TickGuest=tickGuest;tickGuest=function(dt){w123TickGuest(dt);if(!WORLD123.ready||state.mode!=='playing'||road09Duel()||performance.now()-net.receivedAt>600)return;WORLD123.clock+=dt;for(const t of WORLD123.trains)t.s=w123mod(t.s+t.speed*dt,WORLD123.rail.len);w123Positions();w123Crossings(dt);if(WORLD123.wreck)WORLD123.wreck.remaining=Math.max(0,WORLD123.wreck.remaining-dt);w123HUD();};
// Correct map semantics: the route-trial panel is only an explicitly named submenu.
mapMetrics=function(canvas){const w=canvas.width,h=canvas.height,large=w>=300,pad=large?27:13,focus=state.view==='outside'?player.p:car.p,scale=large?Math.min((w-pad*2)/800,(h-pad*2)/800):(Math.abs(car.speed)>17?.60:.78),cx=large?0:focus[0],cz=large?0:focus[2];return{w,h,pad,scale,cx,cz,x:x=>w/2+(x-cx)*scale,z:z=>h/2+(z-cz)*scale};};
function w123RailMap(canvas,large){if(!WORLD123.rail||road09Duel())return;const c=canvas.getContext('2d'),m=mapMetrics(canvas);c.save();c.lineJoin='round';const path=()=>{c.beginPath();WORLD123.rail.points.forEach((p,i)=>i?c.lineTo(m.x(p[0]),m.z(p[2])):c.moveTo(m.x(p[0]),m.z(p[2])));};path();c.lineWidth=large?4.5:5;c.strokeStyle='#182630';c.stroke();path();c.setLineDash([3,3]);c.lineWidth=large?2.1:2.6;c.strokeStyle='#dba6dd';c.stroke();c.setLineDash([]);for(const t of WORLD123.trains){const q=pathAt(WORLD123.rail,t.s);c.fillStyle=t.id?'#c9b9fb':'#e9a174';c.fillRect(m.x(q.p[0])-2.5,m.z(q.p[2])-2.5,5,5);}for(const q of WORLD123.crossings){c.strokeStyle=q.warning?'#ff7c68':'#ead7b2';c.lineWidth=1.5;c.strokeRect(m.x(q.x)-3.5,m.z(q.z)-3.5,7,7);}if(large){c.font='10px Arial';c.fillStyle='#dfbce4';c.fillText('虚线 · 铁路   □ 平交道口',14,m.h-29);}c.restore();}
async function world123Init(){await w123Load('trains');await w123Load('terrain');w123Rail();w123Crossings(2);CD123Boot.mark('init:rail','铺设原生铁路与道口');await new Promise(r=>setTimeout(r,0));w123Infill();CD123Boot.mark('init:infill','补齐城市边缘街区');await new Promise(r=>setTimeout(r,0));w123Terrain();w123BatchScenery();CD123Boot.mark('init:terrain','构建地形支撑与远景');const alert=document.createElement('div');alert.id='railAlert123';alert.hidden=true;alert.setAttribute('role','status');$('game').append(alert);CD123Boot.mark('init:map','连接全城地图与导航');WORLD123.ready=true;}
// Test-only inspection is gated by the existing local test query, never enabled by default.
if(new URLSearchParams(location.search).has('test')){
 window.__world123={info:()=>({ready:WORLD123.ready,models:WORLD123.assets,railLength:WORLD123.rail?.len,railTiles:WORLD123.railTiles?.length,trains:WORLD123.trains.length,units:WORLD123.units.length,crossings:WORLD123.crossings.map(c=>({x:c.x,z:c.z,s:c.s,closed:c.closed,warning:c.warning,eta:c.eta})),infill:WORLD123.infill.length,terrain:WORLD123.terrain.length,trees:WORLD123.trees,static:WORLD123.static.length,batches:WORLD123.batches?.length,draws:WORLD123.draws,signs:V0105.gantries,boot:{done:CD123Boot.done.size,total:CD123Boot.total,ready:CD123Boot.ready,error:CD123Boot.error,history:CD123Boot.history}}),raw:()=>WORLD123,car:()=>car,state:()=>state,net:()=>net,cargo:()=>cargo,packages:()=>packages,player:()=>player,levels:road09Levels,terrainLevels:w123TerrainLevels,overlap:w123Overlap,step:(dt=.016)=>step(dt),railStep:(dt,old)=>w123Step(dt,old||{p:car.p.slice(),yaw:car.yaw}),positions:w123Positions,nearest:w123NearestRail,rescue:w123Rescue,wreck:w123Wreck,snapshot:netSnapshot,apply:applyHostSnapshot,draw:()=>{updateCamera(1);draw3D();},metrics:id=>mapMetrics($(id)),reset:()=>resetGame(false),crossings:w123Crossings,gateMatrix:w123GateMatrix,model:(k,n)=>city012Asset(k,n),matrix:M,gantryAsset:()=>road09.assets.get('sign-highway'),collision:ind012SAT,trafficOff:()=>{for(const t of traffic)t.phase='cleared';for(const t of road09.npc)t.phase='cleared';},camera:(e,a)=>{eye=e;at=a;draw3D();},renderMap:(id,large)=>renderCityMap($(id),large)};
}
