/* Crash Delivery V0.12.0 — City Expansion.
 * Additive extension of the V0.11.2 playable snapshot. All resources are local.
 * Deterministic city layout; render geometry, parcel facades and vehicle colliders
 * share the same normalized GLB transforms. Metres, seconds, tonne ratios.
 */
var CITY012={ready:false,error:'',loaded:0,total:54,assets:new Map(),meshes:new Map(),cars:new Map(),commercial:[],props:[],chunks:[],roads:[],deckSurfaces:[],rails:[],railGrid:new Map(),built:false,nav:null,drawCalls:0,triangles:0,loadMs:0};
const C12_MODELS={commercial:[...'abcdefghijklmn'].map(x=>'building-'+x).concat([...'abcde'].map(x=>'building-skyscraper-'+x),['detail-awning','detail-parasol-a']),cars:['sedan','hatchback-sports','suv','suv-luxury','taxi','van','delivery','truck','truck-flat','ambulance','firetruck','garbage-truck','tractor-shovel','tractor','debris-bumper','debris-door','debris-tire','cone'],environment:['tree','tree-pine','tree-pine-small','hedge','plant','flowers','grass','rocks','stones','crate','crate-strong','barrel','pipe','fence-low-straight','fence-broken']};
const C12_PORTALS={
 'building-a':[['door',.22179,.135,-.33,.20,.27],['window',-.17821,.155,-.33,.20,.19]],
 'building-d':[['door',.2,.135,-.39,.20,.27],['window',-.2,.155,-.39,.20,.19]],
 'building-e':[['door',.2,.135,-.33605,.14,.27],['window',-.2,.2,-.33605,.2,.1]],
 'building-f':[['door',-.2,.135,-.325,.20,.27],['window',.2,.19,-.325,.20,.12]],
 'building-i':[['door',0,.135,-.569,.20,.27],['window',-.4,.155,-.569,.2,.19],['window',.4,.155,-.569,.2,.19]],
 'building-k':[['door',.02179,.135,-.369,.20,.27],['window',-.57821,.155,-.369,.6,.19],['window',.62179,.155,-.369,.6,.19]]
};
const C12_CARS={ // body length, mass ratio, acceleration, city cruise, bend speed
 sedan:[4.5,1.35,3.6,9.1,4.8], 'hatchback-sports':[4.25,1.2,4.1,9.5,5.1],suv:[4.8,1.9,3.1,8.8,4.4],'suv-luxury':[4.95,2.1,3.2,8.9,4.2],taxi:[4.65,1.5,3.8,9.3,4.8],van:[5.4,2.2,2.9,8.4,4.0],delivery:[5.8,2.8,2.6,8.2,3.8],truck:[6.4,4.1,2.0,7.8,3.4],'truck-flat':[6.2,3.6,2.3,8,3.6],ambulance:[5.8,3.0,3.1,8.8,3.9],firetruck:[6.8,5.8,1.9,7.7,3.1],'garbage-truck':[6.6,6.1,1.65,6.9,3.0],'tractor-shovel':[4.7,4.0,1.8,5.8,2.8],tractor:[4.2,2.7,1.8,5.6,2.8]
};
function city012Boot(){const ok=!!CITY012?.ready;for(const id of ['startBtn','roadStart09','hostBtn','joinBtn']){const el=$(id);if(el)el.disabled=!ok;}const el=$('suburbanLoad011');if(el){el.textContent=CITY012?.error?'V0.12 加载失败：'+CITY012.error+'。请确认 assets 文件夹完整后刷新。':ok?'V0.12 城市已就绪 · '+SUB011.homes.length+' 栋住宅/商业楼 · H1 / H2 / H3 高速':'V0.12 正在准备城市 · 新素材 '+(CITY012?.loaded||0)+' / 54';el.style.color=CITY012?.error?'#ffd0a8':'#d1e2cd';}}
function city012Transform(raw,m,out=new MeshBuilder()){for(let i=0;i<raw.length;i+=9)out.a.push(...M.point(m,raw.slice(i,i+3)),...M.normal(m,raw.slice(i+3,i+6)),...raw.slice(i+6,i+9));return out;}
function city012Bake(b,label='detail',cell=48){const groups=new Map();for(let i=0;i<b.a.length;i+=27){const r=b.a,cx=(r[i]+r[i+9]+r[i+18])/3,cz=(r[i+2]+r[i+11]+r[i+20])/3,key=Math.floor(cx/cell)+','+Math.floor(cz/cell);let g=groups.get(key);if(!g){g=new MeshBuilder();groups.set(key,g);}for(let j=0;j<27;j++)g.a.push(r[i+j]);}for(const [key,g]of groups){const[x,z]=key.split(',').map(Number);CITY012.chunks.push({label,mesh:renderer.mesh(g),center:[x*cell+cell/2,label==='highway'?10:2,z*cell+cell/2],radius:cell*.78});}}
function city012Asset(kind,name){return CITY012.assets.get(kind+'/'+name);}
function city012Model(kind,name,p,yaw,scale){const a=city012Asset(kind,name);return M.multiply(scaled(M.model(p,[0,yaw,0]),scale),M.model(V.mul(a.bounds.center,-1)));}
function city012AddStatic(kind,name,p,yaw,scale,b){const a=city012Asset(kind,name);if(!a)throw Error('Missing selected model '+kind+'/'+name);city012Transform(a.b.a,city012Model(kind,name,p,yaw,scale),b);}
async function city012LoadPack(kind){const image=new Image(),palette=await new Promise((res,rej)=>{image.onload=()=>{const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(image,0,0);res({data:x.getImageData(0,0,c.width,c.height).data,w:c.width,h:c.height});};image.onerror=()=>rej(Error(kind+' 调色板缺失'));image.src='./assets/kenney-'+kind+'/Textures/colormap.png';});const loader=new RoadGLB09(palette.data,palette.w,palette.h);let cursor=0;
 const worker=async()=>{while(cursor<C12_MODELS[kind].length){const name=C12_MODELS[kind][cursor++],url='./assets/kenney-'+kind+'/'+name+'.glb',r=await fetch(url);if(!r.ok)throw Error(url+' HTTP '+r.status);const bytes=new Uint8Array(await r.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=32768)text+=String.fromCharCode(...bytes.subarray(i,i+32768));const a=loader.load(name,btoa(text));a.bounds=ind012Bounds(a);CITY012.assets.set(kind+'/'+name,a);CITY012.meshes.set(kind+'/'+name,renderer.mesh(a.b));CITY012.loaded++;city012Boot();}};await Promise.all([worker(),worker(),worker()]);}
// --- Continuous ribbons. Every visible deck triangle also enters the native support grid. ---
function city012Smooth(points,spacing=3){const out=[];for(let j=0;j<points.length-1;j++){const a=points[Math.max(0,j-1)],b=points[j],c=points[j+1],d=points[Math.min(points.length-1,j+2)],n=Math.max(2,Math.ceil(V.len(V.sub(c,b))/spacing));for(let i=0;i<n;i++){const t=i/n,t2=t*t,t3=t2*t;out.push([0,1,2].map(k=>.5*((2*b[k])+(-a[k]+c[k])*t+(2*a[k]-5*b[k]+4*c[k]-d[k])*t2+(-a[k]+3*b[k]-3*c[k]+d[k])*t3)));}}out.push(points.at(-1).slice());return out;}
function city012Road(id,name,points,width,kind='highway',smooth=false){const pts=smooth?city012Smooth(points):points,road={id,name,points:pts,width,kind,path:polyPath(pts,'city012-'+id)};CITY012.roads.push(road);return road;}
function city012Line(a,b,spacing=3){const n=Math.ceil(V.len(V.sub(b,a))/spacing);return Array.from({length:n+1},(_,i)=>V.lerp(a,b,i/n));}
function city012Ramp(id,name,points,width=11){const pts=city012Smooth(points.map(p=>[p[0],.08,p[1]]));const path=polyPath(pts,'ramp'),end=8.08;for(let i=0;i<pts.length;i++){const t=clamp((path.lens[i]-14)/(path.len-42),0,1);pts[i][1]=.08+8*t*t*(3-2*t);}return city012Road(id,name,pts,width,'ramp');}
function city012RoadDistance(p,road){let best={d:Infinity,y:0,t:0,q:null};const pts=road.points;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],dx=b[0]-a[0],dz=b[2]-a[2],den=dx*dx+dz*dz,t=den?clamp(((p[0]-a[0])*dx+(p[2]-a[2])*dz)/den,0,1):0,q=V.lerp(a,b,t),d=Math.hypot(p[0]-q[0],p[2]-q[2]);if(d<best.d)best={d,y:q[1],q,t:road.path.lens[i-1]+V.len(V.sub(q,a))};}return best;}
function city012InJunction(p,owner){return CITY012.roads.some(r=>{if(r===owner)return false;const q=city012RoadDistance(p,r);return q.d<r.width/2+2&&Math.abs(q.y-p[1])<1.2;});}
function city012Rail(a,b,y,r=.17){const c={a,b,minY:y-.05,maxY:y+1.2,r};CITY012.rails.push(c);for(let x=Math.floor((Math.min(a[0],b[0])-5)/16);x<=Math.floor((Math.max(a[0],b[0])+5)/16);x++)for(let z=Math.floor((Math.min(a[2],b[2])-5)/16);z<=Math.floor((Math.max(a[2],b[2])+5)/16);z++){const key=x+','+z;if(!CITY012.railGrid.has(key))CITY012.railGrid.set(key,[]);CITY012.railGrid.get(key).push(c);}}
function city012BuildHighways(){if(!CITY012||CITY012.built)return;CITY012.built=true;
 const ring=[],r=28,centres=[[340,244,0,Math.PI/2],[-244,244,Math.PI/2,Math.PI],[-244,-244,Math.PI,Math.PI*1.5],[340,-244,Math.PI*1.5,TAU]];
 // Clockwise polygon with analytic round corners; append straight sections at 3m intervals.
 for(let k=0;k<centres.length;k++){const[cx,cz,a,b]=centres[k];for(let i=0;i<=18;i++){const u=a+(b-a)*i/18,p=[cx+Math.cos(u)*r,8.08,cz+Math.sin(u)*r];if(i===0&&ring.length)ring.push(...city012Line(ring.at(-1),p).slice(1));else ring.push(p);}}
 ring.push(...city012Line(ring.at(-1),ring[0]).slice(1));city012Road('H1','H1 城市环线',ring,22);
 city012Road('H2','H2 东西快速路',city012Line([-272,8.08,-168],[368,8.08,-168]),20);
 const cross=city012Line([-168,8.08,-272],[-168,8.08,272]);for(const p of cross){const t=Math.min(1,(p[2]+272)/82,(272-p[2])/82);p[1]=8.08+8*t*t*(3-2*t);}city012Road('H3','H3 南北高架',cross,18);
 city012Ramp('R1','西北出口',[[-224,112],[-238,126],[-242,167],[-244,198],[-272,198]]);
 city012Ramp('R2','西南出口',[[-224,-56],[-242,-68],[-246,-110],[-246,-137],[-236,-168]]);
 city012Ramp('R3','向阳北出口',[[0,224],[0,241],[30,247],[74,244],[82,272]]);
 city012Ramp('R4','商业中心出口',[[0,-224],[0,-241],[30,-247],[76,-244],[84,-272]]);
 city012Ramp('R5','工业区出口',[[112,168],[153,168],[220,181],[294,181],[346,191],[368,211]],12);
 city012Ramp('R6','SKYWAY 连接线',[[304,56],[318,56],[322,90],[340,131],[368,135]],12);
 // A direct city entrance to H2 makes short and long itineraries genuinely different.
 city012Ramp('R7','中央快速路出口',[[-56,-112],[-37,-113],[1,-137],[62,-141],[88,-140],[92,-168]],11);
 const b=new MeshBuilder();
 for(const road of CITY012.roads){const pts=road.points,halfw=road.width/2,rs=pts.map((p,i)=>{const d=V.sub(pts[Math.min(pts.length-1,i+1)],pts[Math.max(0,i-1)]),l=Math.hypot(d[0],d[2])||1;return[-d[2]/l,0,d[0]/l];});
  for(let i=1;i<pts.length;i++){const a=pts[i-1],d=pts[i],ra=rs[i-1],rd=rs[i],L=V.add(a,V.mul(ra,halfw)),R=V.sub(a,V.mul(ra,halfw)),L2=V.add(d,V.mul(rd,halfw)),R2=V.sub(d,V.mul(rd,halfw));const tri1=[L,L2,R2],tri2=[L,R2,R];b.triangle(...tri1,'#596573');b.triangle(...tri2,'#596573');const tileId=12000+CITY012.roads.indexOf(road);for(const tri of [tri1,tri2]){road09Surface(tri,{id:tileId});CITY012.deckSurfaces.push({tri,tileId});}
   if(a[1]>.6){const low=p=>[p[0],p[1]-.42,p[2]];b.quad(L,low(L),low(L2),L2,'#89929c');b.quad(R2,low(R2),low(R),R,'#89929c');b.quad(low(L),low(R),low(R2),low(L2),'#647481');}
   const mid=V.lerp(a,d,.5),len=V.len(V.sub(d,a)),yaw=Math.atan2(d[0]-a[0],d[2]-a[2]),pitch=-Math.atan2(d[1]-a[1],Math.hypot(d[0]-a[0],d[2]-a[2]));
   // Flat painted centre/edge lines, no invisible raised median at merging junctions.
   for(const offset of [-halfw+.6,halfw-.6]){const p=V.add(mid,V.mul(V.norm(V.add(ra,rd)),offset));b.box(.11,.014,len+.05,'#e9ece2',[p[0],p[1]+.018,p[2]],[pitch,yaw,0]);}
   if(!city012InJunction(mid,road)){for(const offset of [-.15,.15]){const p=V.add(mid,V.mul(V.norm(V.add(ra,rd)),offset));b.box(.105,.014,len+.05,'#efc76d',[p[0],p[1]+.021,p[2]],[pitch,yaw,0]);}}
   if(road.width>16&&Math.floor(road.path.lens[i]/5)%2===0)for(const off of [-halfw/2,halfw/2]){const p=V.add(mid,V.mul(V.norm(V.add(ra,rd)),off));b.box(.11,.014,len+.025,'#eef0e4',[p[0],p[1]+.019,p[2]],[pitch,yaw,0]);}
   if(mid[1]>1.1)for(const side of [-1,1]){const p=V.add(mid,V.mul(V.norm(V.add(ra,rd)),side*(halfw-.12)));if(city012InJunction(p,road))continue;b.box(.16,.38,len+.08,'#c3cbd0',[p[0],p[1]+.75,p[2]],[pitch,yaw,0]);if(i%2===0)b.box(.16,.88,.16,'#8b9ca5',[p[0],p[1]+.44,p[2]]);city012Rail(V.add(a,V.mul(ra,side*(halfw-.12))),V.add(d,V.mul(rd,side*(halfw-.12))),Math.min(a[1],d[1]));}
   if(i%18===0&&mid[1]>5&&closestCityRoad(mid).d>10&&!CITY012.roads.some(o=>o!==road&&city012RoadDistance(mid,o).d<o.width/2+2)){b.box(1.3,mid[1]-.5,1.3,'#929ca5',[mid[0],(mid[1]-.5)/2,mid[2]]);const c={x:mid[0],z:mid[2],yaw:0,hw:.65,hd:.65,minY:0,maxY:mid[1]-.5,label:'v012-pier'};industrial012.colliders.push(c);industrial012.reserved.push(c);}
  }
 }
 // Direction gantries: useful names and exit identities rather than floating UI labels.
 for(const[id,p,yaw,text]of [['H1',[-272,8.08,16],0,'H1 CITY LOOP'],['H2',[36,8.08,-168],-Math.PI/2,'H2 DOWNTOWN'],['H3',[-168,16.08,40],Math.PI,'H3 NORTH'],['R5',[280,6.7,181],Math.PI/2,'WORKS EXIT'],['R6',[342,3.6,70],Math.PI/3,'SKYWAY H1']]){const m=M.model(p,[0,yaw,0]);for(const s of [-1,1])b.box(.22,6.5,.22,'#a1afb1',[s*8,3.25,0],[0,0,0],m);b.box(16.3,.22,.22,'#a1afb1',[0,6.3,0],[0,0,0],m);b.box(10,1.55,.18,'#245860',[0,5.65,0],[0,0,0],m);cityText(b,text,[0,5.65,.13],.16,'#edf3de',m);}
 city012Bake(b,'highway');CITY012.triangles=b.a.length/27;city012LayoutIndex();
}
// Furniture relocation rebakes old road geometry and clears the surface grid.
// Reinsert the new deck surfaces on EVERY rebake, not just initial construction.
const city012RoadBakeBase=road09Bake;road09Bake=function(){city012RoadBakeBase();if(CITY012?.built)for(const s of CITY012.deckSurfaces)road09Surface(s.tri,{id:s.tileId});};
// Building placement broad phase: cache only static ROAD footprints, never simplify
// runtime parcel collision. This avoids tens of millions of triangle samples at boot.
function city012LayoutIndex(){if(CITY012.layoutGrid)return;const rects=[];
 const add=o=>{o.id=rects.length;rects.push(o);};
 for(const e of cityEdges){const a=cityNodes[e.a],b=cityNodes[e.b];add({x:(a.x+b.x)/2,z:(a.z+b.z)/2,yaw:Math.atan2(b.x-a.x,b.z-a.z),hw:8.1,hd:e.len/2+8.1,maxY:.2});}
 for(const t of road09.tiles){if(t.city094||!t.drive)continue;const a=road09.assets.get(t.name),bb=ind012Bounds(a),pts=[];for(const x of [bb.min[0],bb.max[0]])for(const z of [bb.min[2],bb.max[2]])pts.push(M.point(t.m,[x,bb.max[1],z]));const xs=pts.map(p=>p[0]),zs=pts.map(p=>p[2]);add({x:(Math.min(...xs)+Math.max(...xs))/2,z:(Math.min(...zs)+Math.max(...zs))/2,yaw:0,hw:(Math.max(...xs)-Math.min(...xs))/2,hd:(Math.max(...zs)-Math.min(...zs))/2,maxY:Math.max(...pts.map(p=>p[1]))});}
 for(const r of CITY012.roads)for(let i=1;i<r.points.length;i++){const a=r.points[i-1],b=r.points[i];add({x:(a[0]+b[0])/2,z:(a[2]+b[2])/2,yaw:Math.atan2(b[0]-a[0],b[2]-a[2]),hw:r.width/2+.2,hd:Math.hypot(b[0]-a[0],b[2]-a[2])/2+.2,maxY:Math.max(a[1],b[1])});}
 const grid=new Map();for(const o of rects){o.radius=Math.hypot(o.hw,o.hd);for(let x=Math.floor((o.x-o.radius)/32);x<=Math.floor((o.x+o.radius)/32);x++)for(let z=Math.floor((o.z-o.radius)/32);z<=Math.floor((o.z+o.radius)/32);z++){const key=x+','+z;if(!grid.has(key))grid.set(key,[]);grid.get(key).push(o);}}
 CITY012.layoutGrid=grid;
}
function city012LotRoads(o,pad,elevatedOnly=false){city012LayoutIndex();const radius=Math.hypot(o.hw+pad,o.hd+pad),seen=new Set();for(let x=Math.floor((o.x-radius)/32);x<=Math.floor((o.x+radius)/32);x++)for(let z=Math.floor((o.z-radius)/32);z<=Math.floor((o.z+radius)/32);z++)for(const r of CITY012.layoutGrid.get(x+','+z)||[]){if(seen.has(r.id)||(elevatedOnly&&r.maxY<2.25))continue;seen.add(r.id);if(Math.hypot(o.x-r.x,o.z-r.z)>radius+r.radius)continue;if(ind012Overlap(o,r,pad))return false;}return true;}
const city012StreetClearBase=ind012StreetClear,city012ElevatedClearBase=ind014ElevatedClear;
ind012StreetClear=function(o,pad=.6){return CITY012?.built?city012LotRoads(o,pad,false):city012StreetClearBase(o,pad);};
ind014ElevatedClear=function(o,pad=7){return CITY012?.built?city012LotRoads(o,pad,true):city012ElevatedClearBase(o,pad);};
// --- Commercial lots: native doors/windows, no pasted-on procedural house shell. ---
function city012CommercialLot(h,name,desiredScale,seed=0){const a=city012Asset('commercial',name),bb=a.bounds,portals=C12_PORTALS[name],nativeFront=portals?portals[0][3]:bb.min[2]+.04,original=[h.x,0,h.z],candidates=cityEdges.map(e=>segmentProjection(original,e)).sort((a,b)=>a.d-b.d);
 for(const scale of [desiredScale,desiredScale*.92,desiredScale*.84])for(const q of candidates.slice(0,h.deliverable?22:5)){const e=q.edge,node=cityNodes[e.a],d=edgeDirection(e.a,e.b),right=[-d[2],0,d[0]],defaultSide=V.dot(V.sub(original,q.q),right)>=0?1:-1,hw=bb.size[0]*scale/2,hd=bb.size[2]*scale/2;if(2*hw>36)continue;
  for(const side of [defaultSide,-defaultSide])for(const delta of [0,-5,5,-10,10]){const u=clamp(q.t*e.len+delta,10+hw,e.len-10-hw),edgeP=[node.x+d[0]*u,0,node.z+d[2]*u],out=V.mul(right,side),yaw=Math.atan2(-out[0],-out[2]),frontage=-(nativeFront-bb.center[2])*scale,setback=2.35,p=V.add(edgeP,V.mul(out,8+setback+Math.max(frontage,hd))),o={name:'commercial/'+name,x:p[0],z:p[2],yaw,scale,hw,hd,height:bb.size[1]*scale,minY:.12,maxY:.12+bb.size[1]*scale,h,role:h.deliverable?'commercial-delivery':'commercial',frontageEdge:e.id,road:edgeP,frontage,setback,portals:portals||[],commercial012:true};
   if(districtAt(o.x,o.z)!=='market'||!ind012StreetClear(o,.25)||!ind014ElevatedClear(o,1.3)||industrial012.reserved.some(r=>ind012Overlap(o,r,1.0))||SUB011.homes.some(r=>ind012Overlap(o,r,1.0)))continue;o.m=sub011Model(o);return o;
  }
 }return null;}
function city012Commercial(){for(const name of C12_MODELS.commercial.filter(n=>n.startsWith('building-'))){const a=city012Asset('commercial',name);SUB011.assets.set('commercial/'+name,a);SUB011.meshes.set('commercial/'+name,CITY012.meshes.get('commercial/'+name));}
 const jobs=houses.filter(h=>h.style==='market'&&h.deliverable),names=['building-a','building-d','building-e','building-f','building-i','building-k'];
 industrial012.reserved=industrial012.reserved.filter(r=>!houses.some(h=>h.style==='market'&&Math.abs(r.x-h.x)<.001&&Math.abs(r.z-h.z)<.001));
 const add=o=>{o.h.commercial012=true;sub011Adopt(o);CITY012.commercial.push(o);};
 jobs.forEach((h,i)=>{const o=city012CommercialLot(h,names[i%6],i===2||i===4||i===5?9.4:11.4);if(!o)throw Error('商业地址 #'+h.num+' 没有可达门面');add(o);});
 for(const h of houses.filter(h=>h.style==='market'&&!h.deliverable)){h.hidden011=true;h.gates=[];}
 let serial=700;
 // Central business skyline first, then regular infill on both sides of every street.
 for(const [j,x,z]of [[0,-84,-84],[1,-28,-84],[2,28,-140],[3,28,-84],[4,-84,-140],[1,-196,-140],[2,84,-196],[0,-140,-196]]){const h={x,z,yaw:0,num:serial++,deliverable:false,done:false,style:'market',district:'market',gates:[]},o=city012CommercialLot(h,'building-skyscraper-'+ 'abcde'[j],12.1);if(o){houses.push(h);add(o);}}
 for(const e of cityEdges){if(CITY012.commercial.length>=94)break;const A=cityNodes[e.a],d=edgeDirection(e.a,e.b),right=[-d[2],0,d[0]];for(const side of [-1,1])for(const t of [.28,.72]){const p=V.add([A.x+d[0]*e.len*t,0,A.z+d[2]*e.len*t],V.mul(right,side*20));if(districtAt(p[0],p[2])!=='market')continue;const h={x:p[0],z:p[2],yaw:0,num:serial++,deliverable:false,done:false,style:'market',district:'market',gates:[]},name='building-'+'abcdefghijklmn'[serial%14],bb=city012Asset('commercial',name).bounds,scale=Math.min(11.6,14.8/bb.size[0]),o=city012CommercialLot(h,name,scale);if(o){houses.push(h);add(o);}}}
 const b=new MeshBuilder();for(const o of CITY012.commercial){const m=o.h.model;b.box(o.hw*2+1.2,.05,o.hd*2+1.2,'#c3c8c6',[0,.035,0],[0,0,0],m);if(o.h.deliverable){const g=o.h.gates[0];b.box(Math.max(g.w+.4,2),.015,Math.max(1,o.setback),'#dcd9c4',[g.x,.075,g.planeZ+o.setback/2],[0,0,0],m);const sign=houseWorld(o.h,[g.x,g.y+g.h/2+.6,g.planeZ+.36]);b.box(1.7,.47,.045,'#285862',sign,[0,o.yaw,0]);cityText(b,String(o.h.num),[g.x,g.y+g.h/2+.6,g.planeZ+.40],.065,'#fff0c5',m);}}
 city012Bake(b,'sidewalk');
 // Rebuild shadows now that commercial native placement is final.
 lighting012BuildShadows();routeClock=cityMapClock=-1;routeCache=null;manifestSignature='';
}
// --- Native vehicles: exact silhouette dimensions and mass-dependent reactions. ---
function city012CarModels(){for(const[name,spec]of Object.entries(C12_CARS)){const a=city012Asset('cars',name),scale=spec[0]/a.bounds.size[2],b=city012Transform(a.b.a,city012Model('cars',name,[0,0,0],Math.PI,scale));CITY012.cars.set(name,{name,mesh:renderer.mesh(b),hw012:a.bounds.size[0]*scale/2,hl012:spec[0]/2,height012:a.bounds.size[1]*scale,mass012:spec[1],accel012:spec[2],cruise:spec[3],turn012:spec[4]});}}
function city012CarChoice(t,highway=false){const k=t.id,zone=districtAt(t.p[0],t.p[2]);if(highway)return['sedan','suv','van','hatchback-sports','suv-luxury','delivery'][k%6];if(zone==='garden')return['sedan','suv','hatchback-sports','van','garbage-truck','suv-luxury'][k%6];if(zone==='works')return['truck','truck-flat','delivery','tractor-shovel','tractor','firetruck','van'][k%7];return['taxi','sedan','taxi','van','suv-luxury','ambulance','hatchback-sports'][k%7];}
function city012ApplyCar(t,highway=false){const name=city012CarChoice(t,highway),m=CITY012.cars.get(name);if(m)Object.assign(t,m,{model012:name});}
const city012ResetTrafficBase=resetCityTraffic;resetCityTraffic=function(){city012ResetTrafficBase();if(CITY012?.cars.size)for(const t of traffic)city012ApplyCar(t);};
const city012InitializeTrafficBase=initializeTraffic;initializeTraffic=function(...args){city012InitializeTrafficBase(...args);if(CITY012?.cars.size)city012ApplyCar(args[0]);};
const city012ThinkTrafficBase=thinkCityTraffic;thinkCityTraffic=function(){city012ThinkTrafficBase();for(const t of traffic)if(t.phase==='normal'&&t.motion==='junction')t.targetSpeed=Math.min(t.targetSpeed,t.turn012||4.5);};
function city012Fragments(t,closing){if(!CITY012.ready||closing<6||state.time-(t.debrisTime012||-100)<2||debris.length>60)return;t.debrisTime012=state.time;for(let i=0;i<Math.min(3,1+Math.floor(closing/10));i++){const name=['debris-bumper','debris-door','debris-tire'][(t.id+i)%3],a=city012Asset('cars',name),s=1.6/Math.max(...a.bounds.size),mesh=CITY012.meshes.get('debris012/'+name)||renderer.mesh(city012Transform(a.b.a,city012Model('cars',name,[0,0,0],0,s)));CITY012.meshes.set('debris012/'+name,mesh);debris.push({mesh,p:V.add(t.p,[(i-1)*.4,1.1,0]),v:[Math.sin(t.yaw+i)*closing*.3,2.5+i,Math.cos(t.yaw+i)*closing*.25],rot:[0,t.yaw,0],spin:[2.4+i,1.1,-2],age:0,life:5,r:.25});}}
function city012Impact(t,n,closing,highway=false){const mass=t.mass012||1.4,vanMass=3.6,j=1.18*closing/(1/vanMass+1/mass),npcDV=j/mass,vanDV=j/vanMass;impact(Math.min(24,vanDV));if(highway){t.hp=Math.max(0,t.hp-closing*3.2);t.phase='damaged';t.stopped=0;t.drift012=V.mul(n,-Math.min(9,npcDV));t.spin012=clamp(closing*.04,-1.3,1.3);}else{damageTraffic(t,Math.max(0,(closing-2.5)**2*.52*vanMass/(vanMass+mass)),V.mul(n,-Math.min(12,npcDV)));if(t.phase==='normal'&&closing>4)t.phase='damaged';}const projected=V.dot(n,carForward());car.speed+=vanDV*projected;car.speed=clamp(car.speed,-5,27.78);car.kick=V.add(car.kick,V.mul(n,Math.min(5,vanDV)*.4));city012Fragments(t,closing);}
const city012RoadResetBase=road09ResetTraffic;road09ResetTraffic=function(){city012RoadResetBase();if(!CITY012?.built)return;for(const n of road09.npc)city012ApplyCar(n,true);const ring=CITY012.roads.find(r=>r.id==='H1');if(!ring)return;for(let i=0;i<12;i++){const reverse=i%2===1,path=polyPath(reverse?ring.points.slice().reverse():ring.points.slice(),'v012-ring'),id=road09.npc.length,n={id,path,progress:(Math.floor(i/2)/6+(reverse?.06:0))*path.len,speed:13,maxSpeed:18+i%3,wait:'',cooldown:0,stopped:0,hp:100,phase:'normal',p:[0,.1,0],yaw:0,target:null,lane012:i%4<2?2.7:7.7,highway012:true};Object.assign(n,road09NPCPoint(n,n.progress));city012ApplyCar(n,true);road09.npc.push(n);}};
road09HitNPC=function(dt,predictionOnly=false){for(const n of road09.npc){if(Math.abs(n.p[1]-car.p[1])>2.7||Math.hypot(n.p[0]-car.p[0],n.p[2]-car.p[2])>5+(n.hl012||2))continue;const hit=overlapVehicles(n);if(!hit)continue;car.p=V.add(car.p,V.mul(hit.normal,hit.depth+.02));const closing=Math.max(0,-V.dot(V.sub(car.velocity,V.mul(n.dir||[0,0,-1],n.speed)),hit.normal));if(!predictionOnly&&closing>2&&n.cooldown<=0){n.cooldown=.65;city012Impact(n,hit.normal,closing,true);road09.stats.contacts++;road091FineCrash(closing,1000+n.id,'高速车辆');}}};
const city012RoadStepBase=road09StepTraffic;road09StepTraffic=function(dt){city012RoadStepBase(dt);for(const n of road09.npc){if(n.phase!=='normal'&&n.drift012){const old=n.p.slice();n.p=V.add(n.p,V.mul(n.drift012,dt));n.drift012=V.mul(n.drift012,Math.exp(-2.3*dt));n.yaw+= (n.spin012||0)*dt;n.spin012*=Math.exp(-2.3*dt);const y=road09Support(n.p[0],n.p[2],old[1]+.2).y;if(Math.abs(y-old[1])<.65)n.p[1]=y+.02;else{n.p=old;n.drift012=[0,0,0];}}}};
// --- Environmental details. Static props are batched; a bounded pool can be bumped. ---
function city012Prop(kind,name,p,yaw,scale,dynamic=false){const a=city012Asset(kind,name),o={id:CITY012.props.length,kind,name,p:p.slice(),home:p.slice(),yaw,rot:[0,yaw,0],scale,r:Math.max(.22,Math.min(.7,Math.max(a.bounds.size[0],a.bounds.size[2])*scale/2)),height:a.bounds.size[1]*scale,dynamic,v:[0,0,0],spin:[0,0,0],awake:false,age:0};o.m=city012Model(kind,name,p,yaw,scale);CITY012.props.push(o);return o;}
function city012Decor(){const b=new MeshBuilder(),staticProps=[];let serial=0;const allLots=[...SUB011.homes,...industrial012.placements.filter(o=>o.role==='building'||o.role==='infill'||o.role==='main')];
 for(const o of allLots){const h=o.h||o,zone=districtAt(o.x,o.z);for(const side of [-1,1]){const p=houseWorld(h,[side*(o.hw+1.05),.08,-o.hd*.60]);if(!Number.isFinite(p[0])||closestCityRoad(p).d<9.3||SUB011.homes.some(v=>v!==o&&Math.abs(v.x-p[0])<v.hw+1&&Math.abs(v.z-p[2])<v.hd+1)||CITY012.roads.some(r=>{const q=city012RoadDistance(p,r);return q.d<r.width/2+1&&q.y<5;}))continue;const name=zone==='works'?['pipe','crate-strong','fence-broken'][serial%3]:zone==='market'?['tree','hedge','flowers'][serial%3]:['tree-pine','tree','hedge','plant','flowers','tree-pine-small'][serial%6];const a=city012Asset('environment',name),height=name==='tree'?4.1:name.includes('tree')?4.7:name==='pipe'?1.3:name.includes('hedge')?1.0:.55,scale=height/a.bounds.size[1];city012AddStatic('environment',name,p,serial*.71,scale,b);staticProps.push({p,name});serial++;}
  if(o.h?.deliverable&&zone!=='market'){const g=o.h.gates[0],p=houseWorld(o.h,[o.hw+1.3,.10,Math.max(0,o.hd*.30)]);if(closestCityRoad(p).d>9.3){const name=zone==='works'?'barrel':'crate',a=city012Asset('environment',name);city012Prop('environment',name,p,o.yaw,.85/a.bounds.size[1],true);}}
 }
 // District parks / green buffers fill larger vacant plots without obscuring junctions.
 for(let z=-210;z<=210;z+=28)for(let x=-238;x<=130;x+=28){const p=[x,.08,z];if(closestCityRoad(p).d<13||SUB011.homes.some(o=>Math.hypot(o.x-x,o.z-z)<Math.hypot(o.hw,o.hd)+3)||industrial012.reserved.some(o=>Math.abs(o.x-x)<(o.hw||5)+3&&Math.abs(o.z-z)<(o.hd||5)+3)||CITY012.roads.some(r=>city012RoadDistance(p,r).d<r.width/2+2))continue;const name=['tree-pine','tree','rocks','grass','stones','plant'][serial%6],a=city012Asset('environment',name),height=name.includes('tree')?4.6:name==='rocks'?.85:.28;city012AddStatic('environment',name,p,serial*.5,height/a.bounds.size[1],b);staticProps.push({p,name});serial++;}
 // Store frontage furniture uses the actual Commercial pack, kept clear of the delivery aperture.
 for(const o of CITY012.commercial.filter(o=>!o.h.deliverable).slice(0,12)){const name=o.h.num%2?'detail-awning':'detail-parasol-a',p=houseWorld(o.h,[o.hw*.70,.09,o.hd+1.25]);if(closestCityRoad(p).d>8.6){const a=city012Asset('commercial',name);city012AddStatic('commercial',name,p,o.yaw,1.9/a.bounds.size[1],b);}}
 // Road cones / loose containers are physical, but not placed in the only driving lane.
 for(const road of CITY012.roads.filter(r=>r.kind==='ramp')){const q=pathAt(road.path,5),r=[-q.dir[2],0,q.dir[0]],p=V.add(q.p,V.mul(r,road.width/2+1)),a=city012Asset('cars','cone');city012Prop('cars','cone',p,0,.65/a.bounds.size[1],true);}
 // Heavy clutter around the industrial loading yards, never in a delivery gate.
 for(const o of industrial012.placements.filter(o=>o.role==='building'||o.role==='infill'||o.role==='main').slice(0,9)){const p=[o.x+o.hw+1.8,.09,o.z-o.hd*.65];if(closestCityRoad(p).d>10){const name=o.name.length%2?'crate-strong':'barrel',a=city012Asset('environment',name);city012Prop('environment',name,p,o.yaw,.9/a.bounds.size[1],true);}}
 CITY012.staticPropCount=staticProps.length;CITY012.staticProps=staticProps;city012Bake(b,'environment');
}
function city012StepProps(dt){if(net.mode==='guest')return;let active=0;for(const o of CITY012.props){if(!o.dynamic)continue;if(Math.abs(car.p[1]-o.p[1])<2&&Math.hypot(car.p[0]-o.p[0],car.p[2]-o.p[2])<5.7&&Math.abs(car.speed)>1){const q=vehicleToLocal(o.p);if(Math.abs(q[0])<1.7+o.r&&Math.abs(q[2])<3.85+o.r){o.awake=true;o.age=0;o.v=V.add(V.mul(carForward(),Math.abs(car.speed)*.55),[0,Math.min(4,Math.abs(car.speed)*.18),0]);o.spin=[1.4,2.2,.8];car.speed*=.986;}}
  if(!o.awake)continue;active++;const old=o.p.slice();o.age+=dt;o.v[1]-=12*dt;const next=V.add(o.p,V.mul(o.v,dt));const hit=SUB011.colliders.find(c=>sub011SegmentNear(c,old,next,1)&&segmentBox(houseLocal(c,old),houseLocal(c,next),[-c.hw-o.r,c.minY-o.r,-c.hd-o.r],[c.hw+o.r,c.maxY+o.r,c.hd+o.r]));if(hit){o.v[0]*=-.25;o.v[2]*=-.25;}else o.p=next;const y=road09Support(o.p[0],o.p[2],old[1]+.25).y;if(o.p[1]<y+.02){o.p[1]=y+.02;o.v[1]=Math.abs(o.v[1])>.8?-o.v[1]*.2:0;o.v[0]*=Math.exp(-4*dt);o.v[2]*=Math.exp(-4*dt);o.spin=V.mul(o.spin,Math.exp(-4*dt));}o.rot=V.add(o.rot,V.mul(o.spin,dt));if(o.age>10||(o.age>1.5&&V.len(o.v)<.12)){o.awake=false;o.v=[0,0,0];o.rot[0]=o.rot[2]=0;}if(o.age>24||Math.abs(o.p[0])>412||Math.abs(o.p[2])>412){o.p=o.home.slice();o.awake=false;}}
 CITY012.awakeProps=active;}
// Thin rail segments: SAT uses player rectangle, spatial hash avoids testing the whole highway.
function city012ResolveRails(predictionOnly=false){if(!CITY012.built||road09Duel())return;const list=CITY012.railGrid.get(Math.floor(car.p[0]/16)+','+Math.floor(car.p[2]/16))||[];for(const c of list){if(car.p[1]>c.maxY||car.p[1]+3.3<c.minY)continue;const dx=c.b[0]-c.a[0],dz=c.b[2]-c.a[2],o={x:(c.a[0]+c.b[0])/2,z:(c.a[2]+c.b[2])/2,yaw:Math.atan2(dx,dz),hw:c.r,hd:Math.hypot(dx,dz)/2,minY:c.minY,maxY:c.maxY},q=ind012SAT(o);if(q){const sp=Math.abs(car.speed);car.p=V.add(car.p,V.mul(q.n,q.depth+.015));car.kick=[0,0,0];car.speed*=.63;if(!predictionOnly&&sp>3&&state.time-(CITY012.railHit||-99)>.4){impact(Math.min(7,sp*.23));CITY012.railHit=state.time;}}}}
const city012CarBase=stepCar;stepCar=function(dt,predictionOnly=false){city012CarBase(dt,predictionOnly);city012ResolveRails(predictionOnly);};
// New deck undersides block upward throws as well as downward landings; bounded sweep substeps.
const city012ParcelBase=stepWorldPackage;stepWorldPackage=function(p,dt){const old=p.p.slice();city012ParcelBase(p,dt);if(!CITY012.built||p.delivered||net.mode==='guest')return;const next=p.p.slice(),length=V.len(V.sub(next,old)),steps=Math.min(96,Math.max(1,Math.ceil(length/.35)));if(next[1]>old[1])for(let i=1;i<=steps;i++){const a=V.lerp(old,next,(i-1)/steps),b=V.lerp(old,next,i/steps);let stopped=false;for(const g of road09Levels(b[0],b[2])){if(g.tile<12000||g.y<.6)continue;const under=g.y-.42-(p.r||.24);if(a[1]<=under&&b[1]>=under){const t=(under-a[1])/Math.max(1e-6,b[1]-a[1]);p.p=V.lerp(a,b,t);p.p[1]-=.008;p.v[1]=-Math.abs(p.v[1])*.23;p.pending=null;p.bounces=(p.bounces||0)+1;stopped=true;break;}}if(stopped)break;}};
const city012StepBase=step;step=function(dt){city012StepBase(dt);if(CITY012.ready&&state.mode==='playing')city012StepProps(dt);};
const city012ResetBase=resetGame;resetGame=function(toMenu=false){city012ResetBase(toMenu);if(CITY012)for(const o of CITY012.props){o.p=o.home.slice();o.rot=[0,o.yaw,0];o.v=[0,0,0];o.awake=false;o.age=0;}CITY012&&(CITY012.navCache=null);};
// Guest props remain host authoritative; bounded 3-tuples, no client-side duplicate impacts.
const city012NetBase=netSnapshot;netSnapshot=function(target=null){const m=city012NetBase(target);if(CITY012.ready)m.city012={revision:1,trafficModels:traffic.map(t=>t.model012),highwayModels:road09.npc.map(t=>t.model012),props:CITY012.props.map(o=>[o.id,qvec(o.p),qvec(o.rot),o.awake?1:0])};return m;};
const city012ApplyBase=applyHostSnapshot;applyHostSnapshot=function(m){city012ApplyBase(m);if(!m.city012||m.seq!==net.lastWorldSeq)return;for(const [list,names]of [[traffic,m.city012.trafficModels],[road09.npc,m.city012.highwayModels]])for(let i=0;i<(names?.length||0);i++){const t=list[i],a=CITY012.cars.get(names[i]);if(t&&a&&t.model012!==names[i])Object.assign(t,a,{model012:names[i]});}for(const row of m.city012.props||[]){const o=CITY012.props[row[0]];if(o){o.p=row[1].slice();o.rot=row[2].slice();o.awake=!!row[3];}}};
// Frustum and distance culling. Buildings use shared native meshes, scenery uses spatial batches.
const city012SubDrawBase=sub011Draw;sub011Draw=function(){if(!SUB011.ready||state.mode==='wardrobe')return;SUB011.draws=0;if(SUB011.yards)renderer.draw(SUB011.yards);const forward=V.norm(V.sub(at,eye)),limit=quality==='low'?142:185;for(const o of SUB011.placements){const d=V.sub([o.x,o.height*.4,o.z],eye),radius=Math.hypot(o.hw||1,o.hd||1,o.height*.5),distance=V.len(d),tall=o.height>27;if(distance-radius>(tall?285:limit)||V.dot(d,forward)<-radius-4)continue;renderer.draw(SUB011.meshes.get(o.name),o.m);SUB011.draws++;}};
function city012Draw(){if(!CITY012?.built||state.mode==='wardrobe')return;CITY012.drawCalls=0;const f=V.norm(V.sub(at,eye));for(const c of CITY012.chunks){if(road09Duel()&&c.label==='highway')continue;const d=V.sub(c.center,eye),lim=c.label==='environment'?(quality==='low'?90:135):215;if(V.len(d)-c.radius>lim||V.dot(d,f)<-c.radius)continue;renderer.draw(c.mesh);CITY012.drawCalls++;}if(!CITY012.ready)return;for(const o of CITY012.props){const d=V.sub(o.p,eye);if(V.len(d)>100||V.dot(d,f)<-3)continue;const a=city012Asset(o.kind,o.name),m=M.multiply(scaled(M.model(o.p,o.rot),o.scale),M.model(V.mul(a.bounds.center,-1)));renderer.draw(CITY012.meshes.get(o.kind+'/'+o.name),m);CITY012.drawCalls++;}}
// --- One navigation graph connects local streets, old SKYWAY and all new ramps. ---
function city012BuildNav(){const nodes=[],edges=[],ids=new Map(),node=p=>{const key=p.map(v=>Math.round(v*20)).join(',');if(ids.has(key))return ids.get(key);const id=nodes.length;nodes.push({id,p:p.slice(),links:[]});ids.set(key,id);return id;},edge=(a,b,pts,speed,name,oneway=false,blockKey=null)=>{if(pts.length<2)return;const path=polyPath(pts,name);if(path.len<.01)return;const e={id:edges.length,a,b,path,speed,name,blockKey};edges.push(e);nodes[a].links.push(e);if(!oneway){const rev={id:edges.length,a:b,b:a,path:polyPath(pts.slice().reverse(),name),speed,name,blockKey};edges.push(rev);nodes[b].links.push(rev);}};
 for(const e of cityEdges){const a=cityNodes[e.a],b=cityNodes[e.b],A=[a.x,.08,a.z],B=[b.x,.08,b.z];edge(node(A),node(B),[A,B],7.2,'街道',false,e.key||roadKey(e.a,e.b));}
 for(const e of road09.edges){const A=road09.nodes.get(e.a).p,B=road09.nodes.get(e.b).p;edge(node(A),node(B),e.path.points,10,'SKYWAY',true);}edge(node([112,.08,56]),node([120,.08,56]),[[112,.08,56],[120,.08,56]],8,'SKYWAY 入口');
 for(const r of CITY012.roads){const cuts=[0,r.path.len];for(const other of CITY012.roads){if(other===r)continue;for(const p of [other.points[0],other.points.at(-1)]){const q=city012RoadDistance(p,r);if(q.d<1.2&&Math.abs(q.y-p[1])<.15)cuts.push(q.t);}}cuts.sort((a,b)=>a-b);const unique=cuts.filter((v,i)=>i===0||v-cuts[i-1]>.05);for(let i=1;i<unique.length;i++){const a=unique[i-1],b=unique[i],A=pathAt(r.path,a).p,B=pathAt(r.path,b).p,pts=[A];for(let k=1;k<r.points.length-1;k++)if(r.path.lens[k]>a+.001&&r.path.lens[k]<b-.001)pts.push(r.points[k]);pts.push(B);edge(node(A),node(B),pts,r.kind==='ramp'?11:23,r.id);}}
 CITY012.nav={nodes,edges};}
function city012NavNear(p){let best=null;for(const e of CITY012.nav.edges){const pts=e.path.points;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],dx=b[0]-a[0],dz=b[2]-a[2],den=dx*dx+dz*dz,t=den?clamp(((p[0]-a[0])*dx+(p[2]-a[2])*dz)/den,0,1):0,q=V.lerp(a,b,t),d=Math.hypot(p[0]-q[0],p[2]-q[2])+Math.abs((p[1]||.08)-q[1])*18;if(!best||d<best.d)best={e,q,d,s:e.path.lens[i-1]+V.len(V.sub(q,a))};}}return best;}
function city012PathSlice(path,a,b){const reverse=a>b;if(reverse)[a,b]=[b,a];const out=[pathAt(path,a).p];for(let i=1;i<path.points.length-1;i++)if(path.lens[i]>a&&path.lens[i]<b)out.push(path.points[i]);out.push(pathAt(path,b).p);return reverse?out.reverse():out;}
function city012Route(p,target){if(!CITY012.nav)return shortestCityPath(p,target);const start=city012NavNear(p),end=city012NavNear(target),{nodes}=CITY012.nav,dist=nodes.map(()=>Infinity),prev=nodes.map(()=>null),used=new Set();dist[start.e.a]=start.s/start.e.speed;dist[start.e.b]=(start.e.path.len-start.s)/start.e.speed;
 for(let pass=0;pass<nodes.length;pass++){let u=-1,best=Infinity;for(let i=0;i<nodes.length;i++)if(!used.has(i)&&dist[i]<best){best=dist[i];u=i;}if(u<0)break;used.add(u);for(const e of nodes[u].links){const cost=e.path.len/e.speed+(e.blockKey&&cityBlocked.has(e.blockKey)?120:0);if(dist[u]+cost<dist[e.b]){dist[e.b]=dist[u]+cost;prev[e.b]=e;}}}
 const endA=dist[end.e.a]+end.s/end.e.speed,endB=dist[end.e.b]+(end.e.path.len-end.s)/end.e.speed;let goal=endA<endB?end.e.a:end.e.b;const list=[];let root=goal;for(let i=0;prev[root]&&i<nodes.length;i++){const e=prev[root];list.unshift(e);root=e.a;}
 let points=city012PathSlice(start.e.path,start.s,root===start.e.a?0:start.e.path.len),names=list.map(e=>e.name);for(const e of list)points.push(...e.path.points.slice(1));points.push(...city012PathSlice(end.e.path,goal===end.e.a?0:end.e.path.len,end.s).slice(1));if(start.e.id===end.e.id){points=city012PathSlice(start.e.path,start.s,end.s);names=[start.e.name];}
 const path=polyPath(points,'navigation012');return{points,length:path.len+Math.hypot(p[0]-start.q[0],p[2]-start.q[2])+Math.hypot(target[0]-end.q[0],target[2]-end.q[2]),blocked:false,edges:[],target,highways:[...new Set(names.filter(n=>/^H[123]$/.test(n)))],seconds:Math.min(endA,endB)};}
const city012RouteBase=getCityRoute;getCityRoute=function(force=false){if(!CITY012?.ready||road09Duel())return city012RouteBase(force);const now=performance.now(),h=nextHouse();if(!h)return null;if(!force&&routeCache&&routeCache.order===h.num&&now-routeClock<650)return routeCache;const o=SUB011.homes.find(o=>o.h===h),target=o?.road||houseWorld(h,[0,.08,8]),p=state.view==='outside'?[player.p[0],player.p[1]-WALK_EYE,player.p[2]]:car.p;routeClock=now;return routeCache={...city012Route(p,target),order:h.num};};
// Whole-city map is deliberately not stretched over the original 320m box.
mapMetrics=function(canvas){const w=canvas.width,h=canvas.height,pad=w<300?13:27,large=w>=300,scale=large?Math.min((w-pad*2)/730,(h-pad*2)/610):.67,cx=large?48:car.p[0],cz=large?0:car.p[2];return{w,h,pad,scale,cx,cz,x:x=>w/2+(x-cx)*scale,z:z=>h/2+(z-cz)*scale};};
const city012MapBase=renderCityMap;renderCityMap=function(canvas,large=false){if(!CITY012?.built)return city012MapBase(canvas,large);const c=canvas.getContext('2d'),m=mapMetrics(canvas);c.clearRect(0,0,m.w,m.h);c.fillStyle='#182f3b';c.fillRect(0,0,m.w,m.h);const line=(pts,col,w)=>{c.strokeStyle=col;c.lineWidth=w;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(m.x(p[0]),m.z(p[2])):c.moveTo(m.x(p[0]),m.z(p[2])));c.stroke();};c.lineCap=c.lineJoin='round';
 for(const e of cityEdges)line([[cityNodes[e.a].x,0,cityNodes[e.a].z],[cityNodes[e.b].x,0,cityNodes[e.b].z]],'#69878c',large?5.5:7);
 for(const e of road09.edges)line(e.path.points,'#81a5a0',large?4:5);
 for(const r of CITY012.roads)line(r.points,r.kind==='ramp'?'#c49a62':r.id==='H3'?'#e2bd76':'#e5a758',large?(r.kind==='ramp'?3:6):(r.kind==='ramp'?4:8));
 for(const h of houses){if(h.hidden011)continue;const dim=cityFilter!=='all'&&h.district!==cityFilter;c.globalAlpha=dim?.2:1;const selected=h===nextHouse()||large&&citySelected===h.num;c.fillStyle=h.done?'#7cbf9a':selected?'#fff0b4':h.style==='market'?'#a4b5c6':h.style==='works'?'#b79876':'#76a788';const r=h.deliverable?(selected?4:3):1.7;c.fillRect(m.x(h.x)-r,m.z(h.z)-r,r*2,r*2);if(large&&h.deliverable){c.font='bold 11px Arial';c.textAlign='center';c.fillText(String(h.num),m.x(h.x),m.z(h.z)-8);}}c.globalAlpha=1;
 const route=getCityRoute();if(route)line(route.points,'#bceee0',large?2.6:2.3);
 for(const t of [...traffic,...road09.npc]){if(t.phase==='cleared')continue;c.fillStyle=t.phase==='normal'?'#d1e6da':'#ed886b';c.fillRect(m.x(t.p[0])-1.3,m.z(t.p[2])-1.3,2.6,2.6);}
 for(const p of packages){if(p.delivered)continue;c.strokeStyle='#ffc889';c.strokeRect(m.x(p.p[0])-2.5,m.z(p.p[2])-2.5,5,5);}
 c.save();c.translate(m.x(car.p[0]),m.z(car.p[2]));c.rotate(-car.yaw);c.fillStyle='#fff6d5';c.strokeStyle='#122c39';c.lineWidth=1.5;c.beginPath();c.moveTo(0,-8);c.lineTo(5.5,6);c.lineTo(0,3);c.lineTo(-5.5,6);c.closePath();c.fill();c.stroke();c.restore();
 if(large){c.font='bold 12px Arial';c.textAlign='left';c.fillStyle='#f8dda5';c.fillText('N ↑   V0.12',14,18);for(const[text,x,z]of [['H1',-293,0],['H2',218,-179],['H3',-185,184],['SKYWAY',226,46]])c.fillText(text,m.x(x),m.z(z));c.font='11px Arial';c.fillStyle='#c6dfd7';c.fillText('H1 / H2 / H3 · 快速路     绿色 · 当前导航',14,m.h-14);}
};
drawMap=function(){const now=performance.now();if(now-lastMapDraw<170)return;lastMapDraw=now;renderCityMap($('minimap'));};
const city012HUDBase=updateHUD;updateHUD=function(){city012HUDBase();if(!CITY012?.ready)return;const p=road09View(),near=CITY012.roads.map(r=>({r,q:city012RoadDistance(p,r)})).filter(x=>x.q.d<x.r.width/2+1&&Math.abs(x.q.y-(car.p[1]-.04))<1).sort((a,b)=>a.q.d-b.q.d)[0],old=p[0]>138&&p[0]<334&&p[2]>-48&&p[2]<112,el=$('roadHUD09');if(!road09.trial&&!old){el?.classList.toggle('hidden',!near||state.mode==='menu');const chip=$('districtChip');if(chip)chip.textContent=near?near.r.name+' · 100':DISTRICTS[districtAt(p[0],p[2])].name;if(near){$('roadStep09').textContent=near.r.name;$('roadHeight09').textContent='桥面 '+Math.max(0,car.p[1]-.12).toFixed(1)+' m';}}};
// Complete readiness is all-or-nothing: no half-loaded invisible commercial facades.
async function city012Init(){const start=performance.now();city012Boot();try{for(const kind of ['commercial','cars','environment'])await city012LoadPack(kind);for(let i=0;!SUB011.ready&&i<1500;i++){if(SUB011.error||industrial012.error)throw Error(SUB011.error||industrial012.error);await new Promise(r=>setTimeout(r,40));}if(!SUB011.ready)throw Error('住宅/工业区加载超时');city012BuildHighways();city012Commercial();city012CarModels();for(const t of traffic)city012ApplyCar(t);road09ResetTraffic();city012Decor();city012BuildNav();CITY012.ready=true;CITY012.loadMs=performance.now()-start;window.__city012Ready=true;city012Boot();const v=$('roadStart09');if(v)v.querySelector('span').textContent='SKYWAY / V0.12';document.title='Crash Delivery · V0.12 City Expansion';console.info('Crash Delivery V0.12 ready',city012Info());}catch(e){CITY012.error=e.message;console.error('V0.12:',e);city012Boot();}}
function city012Info(){return{version:'0.12.0',ready:CITY012.ready,error:CITY012.error,assets:CITY012.assets.size,cityNodes:cityNodes.length,streetEdges:cityEdges.length,residential:SUB011.homes.filter(o=>!o.commercial012).length,commercial:CITY012.commercial.length,skyscrapers:CITY012.commercial.filter(o=>o.name.includes('skyscraper')).length,industrial:industrial012.placements.filter(o=>o.role==='building'||o.role==='infill'||o.role==='main').length,orders:TOTAL,roads:CITY012.roads.map(r=>({id:r.id,kind:r.kind,length:+r.path.len.toFixed(1),width:r.width,from:r.points[0],to:r.points.at(-1)})),cityTraffic:traffic.length,highwayTraffic:road09.npc.length,staticProps:CITY012.staticPropCount||0,dynamicProps:CITY012.props.length,chunks:CITY012.chunks.length,loadMs:Math.round(CITY012.loadMs),protocol:NET_PROTOCOL};}
if(window.__deliveryTest)window.__deliveryTest.city012={
 info:city012Info,
 audit:()=>({overlaps:SUB011.homes.flatMap((a,i)=>SUB011.homes.slice(i+1).filter(b=>ind012Overlap(a,b,0)).map(b=>[a.h.num,b.h.num])),roadConflicts:SUB011.homes.filter(o=>!ind012StreetClear(o,.1)).map(o=>o.h.num),gates:deliverable.map(h=>({num:h.num,count:h.gates.length,district:h.district,p:[h.x,h.z]})),unplaced:deliverable.filter(h=>h.style!=='works'&&!h.suburban011).map(h=>h.num),surfaceMisses:CITY012.roads.flatMap(r=>r.points.filter((p,i)=>i%3===0&&!road09Levels(p[0],p[2]).some(g=>Math.abs(g.y-p[1])<.08)).slice(0,3).map(p=>({id:r.id,p}))),grades:CITY012.roads.map(r=>({id:r.id,max:Math.max(...r.points.slice(1).map((p,i)=>Math.abs(p[1]-r.points[i][1])/Math.hypot(p[0]-r.points[i][0],p[2]-r.points[i][2])))}))}),
 nav:(p,t)=>city012Route(p,t),
 connected:()=>{const n=CITY012.nav.nodes,seen=new Set([0]),q=[0];for(let i=0;i<q.length;i++)for(const e of n[q[i]].links)if(!seen.has(e.b)){seen.add(e.b);q.push(e.b);}return{total:n.length,reached:seen.size,missed:n.filter(o=>!seen.has(o.id)).map(o=>o.p)};},
 roads:()=>CITY012.roads.map(r=>({id:r.id,points:r.points,path:r.path,width:r.width})),
 cars:()=>[...traffic,...road09.npc].map(t=>({id:t.id,model:t.model012,p:t.p,yaw:t.yaw,speed:t.speed,phase:t.phase,mass:t.mass012,width:t.hw012*2,length:t.hl012*2,height:t.height012})),
 warp:(p,yaw=0)=>{state.mode='playing';state.view='drive';car.p=p.slice();car.yaw=yaw;car.speed=0;car.kick=[0,0,0];car.velocity=[0,0,0];car.roadPitch=0;car.roadVy=0;state.switchUntil=0;},
 drive:(seconds,keys=['KeyW'])=>{inputs.keys=new Set(keys);for(let i=0;i<Math.ceil(seconds*120);i++){state.time+=1/120;stepCar(1/120,false);}clearInputs();return{p:car.p,speed:car.speed,hp:car.hp,pitch:car.roadPitch};},
 disableTraffic:()=>{for(const t of traffic){t.p=[-400,.1,-400];t.phase='cleared';}for(const n of road09.npc){n.p=[-400,.1,-400];n.phase='parked';n.stopped=-1e8;}},
 camera:(eyeP,atP)=>{road09.debugCamera={eye:eyeP,at:atP};updateCamera(.1);draw3D();},
 raw:()=>({car,props:CITY012.props.map(o=>({id:o.id,name:o.name,p:o.p,v:o.v,awake:o.awake})),houses:SUB011.homes.map(o=>({num:o.h.num,name:o.name,p:[o.x,.12,o.z],yaw:o.yaw,scale:o.scale,height:o.height,hw:o.hw,hd:o.hd,model:Array.from(o.m),gates:o.h.gates.map(g=>({x:g.x,y:g.y,z:g.planeZ,w:g.w,h:g.h}))})),packages:packages.map(p=>({id:p.id,order:p.order,p:p.p,v:p.v,delivered:p.delivered,pending:p.pending,returnToDoor:p.returnToDoor,rest:p.rest012}))}),
 fixture:(order,p,v,extra={})=>{const c=cargo.find(c=>c.order===order);if(!c)throw Error('Fixture parcel missing');cargo.splice(cargo.indexOf(c),1);Object.assign(c,{p:p.slice(),v:v.slice(),rot:[0,0,0],spin:[0,0,0],delivered:false,pending:null,thrown:true,age:0,integrity:100,vehicleSpeed:8},extra);packages.push(c);return c.id;},
 parcelStep:(id,seconds,dt=1/120)=>{const p=packages.find(p=>p.id===id);if(!p)throw Error('No parcel');for(let t=0;t<seconds-1e-8;t+=dt)stepWorldPackage(p,Math.min(dt,seconds-t));return{p:p.p,v:p.v,done:p.delivered,order:p.order,pending:p.pending,rest:p.rest012,returns:p.returnToDoor,bounces:p.bounces};},
 regressionRethrow:(wrong=114,order=113)=>{
  stopNetwork(false);resetGame(false);freezeSimulation=true;for(const t of traffic){t.phase='cleared';t.p=[-400,.1,-400];}for(const n of road09.npc){n.phase='parked';n.stopped=-1e8;n.p=[-400,.1,-400];}
  const h=houses.find(h=>h.num===wrong),o=SUB011.homes.find(o=>o.h===h),g=h.gates[0],p=cargo.find(p=>p.order===order);cargo.splice(cargo.indexOf(p),1);Object.assign(p,{p:houseWorld(h,[g.x,g.y,g.planeZ+8]),v:worldVelocity(h,[0,2,-24]),age:0,thrown:true,delivered:false,pending:null,rot:[0,0,0],spin:[0,0,0]});packages.push(p);for(let i=0;i<70;i++)stepWorldPackage(p,1/120);
  const rejected=!p.delivered&&(p.wrongAt||[]).includes(wrong),returned=p.p.slice();state.mode='playing';state.view='outside';state.switchUntil=0;state.cooldown=0;player.repair=null;player.held=null;player.p=V.add(p.p,worldVelocity(h,[0,0,1.05]));player.p[1]=WALK_EYE+.08;let dir=V.norm(V.sub(p.p,player.p));player.yaw=Math.atan2(-dir[0],-dir[2]);player.pitch=Math.asin(dir[1]);interact();const recovered=player.held===p,cleared=recovered&&!p.returnToDoor&&!p.rest012&&!p.pending&&p.hitNpc===null;
  if(!recovered)return{rejected,recovered,cleared,returned,focus:collectFocus()?.type};
  player.p=houseWorld(h,[o.hw+8,WALK_EYE+.12,0]);dir=worldVelocity(h,[-1,0,0]);player.yaw=Math.atan2(-dir[0],-dir[2]);player.pitch=.005;player.aimHouse=player.aimGate=null;state.cooldown=0;startCharge('rethrow-regression');state.charge=1;finishCharge('rethrow-regression');const released=!player.held&&packages.includes(p);for(let i=0;i<80;i++)stepWorldPackage(p,1/120);const local=houseLocal(h,p.p);return{rejected,recovered,cleared,released,bounces:p.bounces||0,local,blocked:!p.delivered&&(p.bounces||0)>0&&local[0]>0,returned};
 },
 delivery:num=>{const h=houses.find(h=>h.num===num),g=h.gates[0],p=cargo.find(p=>p.order===num);if(!p)throw Error('missing parcel '+num);cargo.splice(cargo.indexOf(p),1);const z=g.planeZ??h.facadeZ??4.4;Object.assign(p,{p:houseWorld(h,[g.x,g.y,z+7]),v:worldVelocity(h,[0,1.8,-24]),age:0,thrown:true,delivered:false,pending:null,rot:[0,0,0],spin:[0,0,0]});packages.push(p);for(let i=0;i<100;i++)stepWorldPackage(p,1/120);return{num,delivered:p.delivered,p:p.p,v:p.v,bounces:p.bounces};},
 deck:(p)=>road09Levels(p[0],p[2]),
 followRoad:(id,reverse=false)=>{const road=CITY012.roads.find(r=>r.id===id),path=polyPath(reverse?road.points.slice().reverse():road.points,'qa');let error=0,contacts=0,maxYError=0;const failures=[];for(let s=2;s<path.len-2;s+=2){const q=pathAt(path,s),right=[-q.dir[2],0,q.dir[0]],p=V.add(q.p,V.mul(right,2.6));car.p=[p[0],p[1]+.04,p[2]];car.yaw=q.yaw;car.speed=8;car.kick=[0,0,0];car.velocity=V.mul(q.dir,8);car.roadVy=0;car.roadPitch=0;state.view='drive';state.switchUntil=0;clearInputs();stepCar(1/120,false);const y=road09Support(car.p[0],car.p[2],q.p[1]+.2).y;const delta=Math.abs(car.p[1]-(y+.04));maxYError=Math.max(maxYError,delta);const moved=Math.hypot(car.p[0]-p[0],car.p[2]-p[2]);if(moved>.6){contacts++;error=Math.max(error,moved);}if((moved>.6||delta>.25)&&failures.length<10)failures.push({s,from:p,to:car.p.slice(),support:y,moved,delta,levels:road09Levels(p[0],p[2]).map(q=>({y:q.y,tile:q.tile}))});}return{id,reverse,maxDisplacement:error,contacts,maxYError,failures};},
 extras:()=>{
  const api=window.__deliveryTest.city012,reset=()=>{window.__deliveryTest.suburban011.reset();api.disableTraffic();car.hp=100;car.fault='';car.steer=0;state.brick=false;};
  reset();api.warp([0,.12,56],0);const street=api.drive(2,['KeyW']);
  reset();api.warp([0,8.12,-165.3],-Math.PI/2);const elevated=api.drive(2,['KeyW']);
  reset();api.warp([0,8.12,-165.3],-Math.PI/2);state.brick=true;const brick=api.drive(2,[]);
  reset();api.warp([0,8.12,-165.3],-Math.PI/2);const t=traffic[0];t.phase='damaged';t.p=[0,.12,-165.3];t.drift=[0,0,0];t.speed=0;t.hitCooldown=0;const ghost=api.drive(.2,['KeyW']);
  reset();const prop=CITY012.props.find(o=>o.dynamic&&o.home[1]<.3),before=prop.p.slice();car.p=V.add(prop.p,[0,.04,3]);car.yaw=0;car.speed=12;city012StepProps(1/60);const bumped={before,after:prop.p.slice(),velocity:prop.v.slice(),awake:prop.awake};for(let i=0;i<1200;i++)city012StepProps(1/120);const asleep=!prop.awake;
  const sample=name=>{reset();const t=traffic[0];Object.assign(t,CITY012.cars.get(name),{model012:name,phase:'normal',hp:100,drift:[0,0,0],speed:0,hitCooldown:0});car.yaw=0;car.speed=14;car.kick=[0,0,0];state.hitCooldown=0;city012Impact(t,[0,0,1],14,false);return{mass:t.mass012,vanSpeed:car.speed,npcSpeed:V.len(t.drift),fragments:debris.filter(d=>d.life===5).length};};const mass={small:sample('hatchback-sports'),heavy:sample('garbage-truck')};
  reset();const p=CITY012.props[0];p.p[0]+=1.25;const expected=p.p.slice(),m=netSnapshot();p.p=p.home.slice();const saved={mode:net.mode,id:net.playerId,epoch:net.seenEpoch,seq:net.lastWorldSeq};net.mode='guest';net.playerId=0;net.seenEpoch=m.epoch;net.lastWorldSeq=m.seq-1;applyHostSnapshot(m);const sync={propCount:m.city012.props.length,trafficModels:m.city012.trafficModels.length,highwayModels:m.city012.highwayModels.length,position:p.p.slice(),expected,match:V.len(V.sub(p.p,expected))<.002};Object.assign(net,{mode:saved.mode,playerId:saved.id,seenEpoch:saved.epoch,lastWorldSeq:saved.seq});
  reset();const h=houses.find(h=>h.num===114),gate=h.gates[0],parcel=cargo[0];parcel.p=[0,2,-168];parcel.v=[0,40,0];parcel.delivered=false;parcel.pending=null;parcel.r=.25;parcel.rot=parcel.spin=[0,0,0];parcel.age=0;for(let i=0;i<20;i++)stepWorldPackage(parcel,1/120);const underside={p:parcel.p.slice(),v:parcel.v.slice(),blocked:parcel.p[1]<7.7&&parcel.v[1]<0};
  reset();return{street,elevated,brick,ghost,prop:bumped,propAsleep:asleep,mass,sync,underside};
 },
 models:()=>Object.fromEntries([...CITY012.assets].map(([k,a])=>[k,{bounds:a.bounds,triangles:a.triangles}])),
 renderDump:()=>({meshes:[...SUB011.homes].map(o=>({kind:'house',name:o.name,m:Array.from(o.m),raw:SUB011.assets.get(o.name).b.a})),roads:CITY012.roads.map(r=>({id:r.id,points:r.points,width:r.width}))})
};
city012Init();
